### ISSUE TITLE
Bearer comparison still not case insensitive in one place

### ISSUE THREAD

**Issue by zzgvh** [OpenIDC/pyoidc#131]
Referring to #130, I see that you fixed the issue with new code that passes your tests rather than my failing fix. 

However the problem was only fixed [here](https://github.com/rohe/pyoidc/blob/1401379c2e62b67a9d5eadd8730a815b9f351cf2/src/oic/oic/__init__.py#L738) but still remains [here](https://github.com/rohe/pyoidc/blob/1401379c2e62b67a9d5eadd8730a815b9f351cf2/src/oic/oic/__init__.py#L705). This manifests when calling the **userinfo_endpoint** on Keycloak.

Oh, and thanks for this great library!

**Comment by tpazderka** [comment]
This seems to be fixed in master already.
