### ISSUE TITLE
Support Client Configuration Endpoint

### ISSUE THREAD

**Issue by gobengo** [OpenIDC/pyoidc#134]
http://openid.net/specs/openid-connect-registration-1_0.html#ClientConfigurationEndpoint

oic.oic.Provider:registration_endpoint works great, and the ClientRegistrationResponse includes the 'registration_client_uri'. However, if I issue GET requests to that URI, I usually get a 400 Bad Request response code. It looks like this is because the GET request is treated the same as a (new) Client Registration Request.

@rohe Is this "Client Read Request" functionality something intentionally omitted? Or would you welcome contributions to implement it?

**Comment by rohe** [comment]
> 9 okt 2015 kl. 20:58 skrev Benjamin Goering <notifications@github.com>:
> 
> http://openid.net/specs/openid-connect-registration-1_0.html#ClientConfigurationEndpoint
> 
> oic.oic.Provider:registration_endpoint works great, and the ClientRegistrationResponse includes the 'registration_client_uri'. However, if I issue GET requests to that URI, I usually get a 400 Bad Request response code. It looks like this is because the GET request is treated the same as a (new) Client Registration Request.
> 
> @rohe Is this ”Client Read Request" functionality something intentionally omitted?

Not intentionally omitted!

> Or would you welcome contributions to implement it?

Yes ! :-)

— Roland
'Look, that's why there's rules, understand? So that you think before you break ’em.’ - Terry Pratchett

**Comment by gobengo** [comment]
Thanks @rohe. I'll work toward a pull request that you and others can weigh in on.

**Comment by tpazderka** [comment]
We do have our own implementation of this, so I can give it a try.

**Comment by tpazderka** [comment]
Eh, sorry. Misread the issue. I am not familiar with the usage of endpoints in this manner.

**Comment by tpazderka** [comment]
It looks like this cannot be done in the current state of the `Endpoint` class. Each endpoint is bound to one function. In order to get this to work, we would have to create a new `Endpoint` subclass that would be doing this. It would be then a question of configuration to distinguish between POST/GET on the same url and pointing to the correct endpoint.

**Comment by schlenk** [comment]
Isn't this implemented in the oic/extension/providers.py code:

https://github.com/OpenIDC/pyoidc/blob/a0dcac099c2b1adb0bd546080175d77c725bc48f/src/oic/extension/provider.py#L449

At least it looks pretty similar.

**Comment by tpazderka** [comment]
You are correct!

The only documented method in OIDC specifications is `GET` so I would definitely move that one to the generic class. The rest probably should remain in the extensions. We should enable easy override of the other methods for users.

I will give it a try later this week.
