### ISSUE TITLE
Should be auth_time decimal or float?

### ISSUE THREAD

**Issue by jtalir** [OpenIDC/pyoidc#171]
Being pyoidc OpenID Connect server, we have received several messages from RP's that auth_time returned from pyoidc is invalid. RP's cannot handle float numbers and expect decimal. There is a request for Google client  to be more liberal and accept float - https://github.com/google/google-oauth-java-client/issues/119, however I've received the same info from people behind https://demo.c2id.com/oidc-client/ (don't know if they are using the same or different library). Maybe it's better to be more conservative on server side and provide decimal instead of float 

Spec only says it's number:

auth_time
    Time when the End-User authentication occurred. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time. When a max_age request is made or when auth_time is requested as an Essential Claim, then this Claim is REQUIRED; otherwise, its inclusion is OPTIONAL. (The auth_time Claim semantically corresponds to the OpenID 2.0 PAPE [OpenID.PAPE] auth_time response parameter.)

**Comment by tpazderka** [comment]
According to (not only) [this reference](http://www.tutorialspoint.com/json/json_data_types.htm) `JSON number` is `float`.
