### ISSUE TITLE
parse_qs from future is not handling unicode

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#189]
Passing unicode string with characters outside range(128) causes `deserialize()` to fail.

It looks like an issue with `parse_qs` imported from `future.backports.urllib.parse`. When the function is imported from `urlparse` (Python 2) or `urllib.parse` (Python 3), the conversion goes without any issues.

**Comment by tpazderka** [comment]
And I have just noticed that the `parse_qs` imported from `future.moves.urllib.parse` works just fine, so it should be possible to change the import to this.

**Comment by lwm** [comment]
> it should be possible to change the import to this.

Thanks for investigating! Feel like adding the fix to this pull request? Would also appreciate a change log entry in `CHANGELOG.md`. Otherwise, I'll move this forward, just let me know :+1:

**Comment by tpazderka** [comment]
Yes, I will do it.

**Comment by tpazderka** [comment]
Fixed only in code. I decided not to change anything in tests or examples.

**Comment by tpazderka** [comment]
Closed by #296
