### ISSUE TITLE
PyOIDC is unable to return empty strings as id token claims

### ISSUE THREAD

**Issue by bjmc** [OpenIDC/pyoidc#209]
If the users DB returns an empty string for a particular claim (in our case, it was `middle_name`) that field will be omitted from id_token, even if it was requested in the `claims` parameter and is returned correctly for other users with non-empty middle names.

The `make_id_token()` function [instantiates an IdToken object](https://github.com/rohe/pyoidc/blob/a895609840c50c7b0b3026f837260fbba5e10a0c/src/oic/oic/__init__.py#L1534) and passes in the userinfo as keyword arguments. 

`IdToken` is a subclass of `oic.oauth2.message.Message` and the parent constructor calls  `Message.from_dict()` on `kwargs`, but [`from_dict()` discards any items with empty string values.](https://github.com/rohe/pyoidc/blob/a895609840c50c7b0b3026f837260fbba5e10a0c/src/oic/oauth2/message.py#L334)

I don't know if that behavior is necessary or desirable on other subclasses of `Message`, but it seems wrong (or at least surprising) in the case of `IdToken`.

The [OpenIDConnect spec says](http://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse):

> If a Claim is not returned, that Claim Name SHOULD be omitted from the JSON object representing the Claims; it SHOULD NOT be present with a null or empty string value.

There's room for interpretation, but I think this is the inverse scenario: If the OIDC server _is_ generally returning that claim, then for users where the value of that claim is '', we SHOULD include the Claim Name, not omit it from the response.

**Comment by tpazderka** [comment]
According to my interpretation of the specs, this should be the correct behavior.

So unles @rohe disagrees, we should close this as `won't fix`.

**Comment by bjmc** [comment]
Can you explain a little more why you think this is correct behavior? Under this interpretation, it becomes impossible for an OIDC provider to ever return a claim with an empty string for a value. Is that desirable?

**Comment by tpazderka** [comment]
It is according to the part you cited. If the value would be represented by a null or empty string value, it should be omitted.

**Comment by bjmc** [comment]
The section I cited in the spec is discussing the inverse of the case I'm questioning here.

The spec is saying:

IF 'Claim **is not** returned' THEN 'Claim Name SHOULD be omitted'

I'm suggesting that:

IF Claim **is** returned (in this case with an empty string value) THEN claim name should not be omitted.

**Comment by tpazderka** [comment]
Oh, I see... Sorry, I misread your comment.

It looks like there is not specification about this. But for example OpenID returns empty values, so we should consider this.

**Comment by bjmc** [comment]
Yeah, I think it's an open question. We should see what other implementations do, and if there's any authoritative guidance from the OpenIDConnect spec authors.

**Comment by rohe** [comment]
RFC6749 which is what OIDC is built on specifically says on authorisation requests:

"Parameters sent without a value MUST be treated as if they were omitted from the request."

I can check with the authors but I'm pretty certain the same goes for ID Tokens though it's not explicitly stated in the standard. 
So I'd go with @tpazderka initial reaction and recommend 'won't fix'.

**Comment by bjmc** [comment]
@rohe It seems like in the section I quoted above, the authors are going to effort to explicitly state that if the OP is omitting a claim, then it needs to really omit it, not return it with a null value.

On the other hand, if they intend for omitted items to be treated equivalently to null-values (as your quote from RFC6749 suggests), then there would be no need to stress the importance of omitting the claim name.

I'd also like to point out that while Python considers both `None` and empty-string to be Falsey, a JSON `null` is *not* the same thing as an empty string. I would read "Parameters sent without a value" as referring only to `null` values. Would you omit a `price: 0` claim?

**Comment by rohe** [comment]
Interesting how one can differ in interpreting text :-)

My interpretation is not the same as yours.
Mine is that if someone is sending you a claim with no value ('' or null) then you MUST remove that claim from the parsed response/request before acting on the response/request. 

If my memory of the discussions are anything to go by this is the 'official' view.

The number 0 is a value.
I know there are libraries that will send you claims with no values. I've seen a couple of them using my test tools. We have not flag it as an error or even an warning. Perhaps we should have.

**Comment by bjmc** [comment]
> Interesting how one can differ in interpreting text :-)

This is why we write programming languages for computers instead of silly ambiguous human languages. : )

> if someone is sending you...

In the spirit of "Be conservative in what you send, be liberal in what you accept", it seems like RFC6749 is telling the OP to go ahead and accept authorization request parameters without values, and treat them as though they were omitted. But in section 5.3.2 of the OIDC spec, the authors are telling OP developers to be careful about what they send, to really omit claims, not send them with null values. That is to say, they're drawing a distinction between an omitted claim and a claim with a null or empty string value.

> The number 0 is a value.

So what counts as "a value" vs "no value"? Is an empty array `[]` a value? Is an empty object `{}` a value? A string is just an array of bytes. Respectfully, [this way lies madness.](https://stackoverflow.com/questions/6003884/how-do-i-check-for-null-values-in-javascript)

If we can get an authoritative answer from the OIDC spec authors, we should follow that. Otherwise, defer to @rohe as project lead.

**Comment by rohe** [comment]
I can check with John and Mike.

**Comment by tpazderka** [comment]
@rohe Thanks!

**Comment by rohe** [comment]
OK, the verdict is in :-)
If it's ID Token we're talking about then you have to look at the definitions of the claims themselves.

Take for instance **nonce** in an ID Token.
Here the standards says:  'The nonce value is a case sensitive string.'
It doesn't state that the string has to be of a length > 0, that's implied.

Likewise for **amr**:
'The amr value is an array of case sensitive strings.'
Again it doesn't say that such an array must have a length >0, it implicit.

Both John and Mike backs me on this so I see no reason to change the IdToken class in pyoidc.

**Comment by bjmc** [comment]
Fair enough. If they're saying that "string" actually implies "string with len > 0", then it's their spec. :slightly_smiling_face:
