### ISSUE TITLE
Feature request: Add support for Resource Owner Password Credentials grant

### ISSUE THREAD

**Issue by bjmc** [OpenIDC/pyoidc#210]
In some scenarios, developers may need to enable the [Resource Owner Password Credentials grant](http://tools.ietf.org/html/rfc6749#section-1.3.3) for use with their OpenID Connect server.

However, it seems like this is currently impossible with PyODIC, because the token endpoint asserts that [`req["grant_type"] == "authorization_code"`](https://github.com/rohe/pyoidc/blob/master/src/oic/oic/provider.py#L902)

Obviously the password grant is less secure and should be avoided where possible, but it [is allowed under the spec](http://stackoverflow.com/questions/24047047/does-openid-connect-support-the-resource-owner-password-credentials-grant) and it would be nice if PyOIDC supported it.

**Comment by rohe** [comment]
> 9 juni 2016 kl. 17:08 skrev Brendan McCollam <notifications@github.com>:
> 
> In some scenarios, developers may need to enable the Resource Owner Password Credentials grant for use with their OpenID Connect server.
> 
> However, it seems like this is currently impossible with PyODIC, because the token endpoint asserts that req["grant_type"] == "authorization_code"
> 
> Obviously the password grant is less secure and should be avoided where possible, but it is allowed under the spec and it would be nice of PyOIDC supported it.

There is presently no support in pyOIDC for other grants type then authorisation_code.
Will add it in the near future.

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain

**Comment by schlenk** [comment]
Implemented via https://github.com/OpenIDC/pyoidc/pull/383
