### ISSUE TITLE
Make a new RTD release

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#253]
Looks like the local copy and the live copy are out of sync?

For example, `Install PyOIDC using Docker` is missing.

Can the Travis CI build take care of deployments?

**Comment by lwm** [comment]
I'm working on a PR that might give the documentation a new lease of life.

**Comment by lwm** [comment]
@rohe can you configure this? You just need to add a web hook to push to RTD when we merge a pull request. Thanks.

**Comment by lwm** [comment]
@rohe, pinging here again, can you also give me access to the RTD setup? I made a pull request to improve the documentation a while back and it is still not synced live.

**Comment by rohe** [comment]
RTD says it's failing to build. Trying to find out why.

**Comment by rohe** [comment]
Seems to be a pyldap problem.
RTD says 'Failed to build pyldap'

**Comment by lwm** [comment]
> RTD says 'Failed to build pyldap'

Ah! That is because it needs some system dependencies. I'll try and seperate that dependency out of the documentation build and ping you again. Thanks for following up!

**Comment by lwm** [comment]
I think after https://github.com/OpenIDC/pyoidc/pull/294 gets merged, we should get a green documentation build. In any case, I wouldn't mind being added to the RTD platform as a maintainer, my username is `decentral1se` and my email is the same as the one you have.
