### ISSUE TITLE
Token endpoint fails to validate incoming parameters?

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#259]
I have the following test:

```
def test_token_missing_params(client):
    data = dict(
        code='c', client_secret='s', 
        client_id='i', redirect_uri='https://x.xyz')
    )
    resp = client.post(url_for('op.token'), data=data)
    assert resp.status_code == 400
```

As you can see, I expect to receive a `HTTP 400`, because I am missing the `grant_type` parameter. Instead, I receive a `HTTP 401`.

Thoughts?

**Comment by rohe** [comment]
I guess it's a matter of in which order the request is evaluated/verified.
The grant_type check comes rather late in the order.

**Comment by tpazderka** [comment]
As per specification, the authorization of the client comes (probably) first. So I guess, that the current behavior is correct.
