### ISSUE TITLE
Question: cookie time outs

### ISSUE THREAD

**Issue by decentral1se** [OpenIDC/pyoidc#263]
When we make a successful request to the verification endpoint, the `verify` function does:

```
headers = [self.create_cookie(_dict["login"][0], "upm")]
```

Then, after the user authenticated and we do the redirection dance, we end up in the `authenticated_as` function, to check if this run should administer a code. The flow follows:

```
if typ == "uam":
    ... # check timeout based on cookie_ttl
if "max_age" in kwargs and kwargs["max_age"]:
    ... # check timeout based on max_age
```

Now, the base auth class, `UserAuthnMethod` only sets a `upm` cookie. So, that means, the `authenticated_as` function will always look for a `max_age` in the authorization request, to see if the cookie is timed out.

My question being: Shouldn't the server control the `max_age`, and not the client request? Because, the client can set `max_age = 0` all the time, and re-use the cookie as much as they want.

As an example, my test is:

```
# This passes ... 
def test_auth_get_with_cookie_too_late(client, auth_params, redis_mock):
    cookie = current_app.provider.cookie_func("foo", "upm", "pyoidc")
    auth_params.update({'max_age': 1})
    query = urlencode(auth_params)
    url = url_for('op.auth')
    headers = Headers({cookie[0]: cookie[1]})
    too_late = dt.now() + timedelta(minutes=5)
    with freeze_time(too_late):
        resp = client.get(url, query_string=query, headers=headers)
        assert resp.status_code == 200
        assert resp.mimetype == 'text/html'
```

Where I can change the `auth_params.update({'max_age':1})` to `0` and get a HTTP 303 (a code was given out) or, when it is set to `1`, I get a HTTP 200 and am asked to login again.

**Comment by rohe** [comment]
Yes, the server should control access.
That is definitely an oversight/security hole.

**Comment by tpazderka** [comment]
This is still present in the code.

**Comment by decentral1se** [comment]
Can you re-open under this project? I'm just trying to clean up issue reports from my side, thanks :zap:
