### ISSUE TITLE
Please make a new PYPI release

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#264]
There have been many bug fixes.

**Comment by rohe** [comment]
Done

**Comment by lwm** [comment]
Thanks!

**Comment by lwm** [comment]
@rohe, sorry, did you make a tagged release on Github, or actually make a release on PyPi?

I can't find a newer version than https://pypi.python.org/pypi/oic/0.9.4.0?

**Comment by rohe** [comment]
I think I did both.
But I can make a new release this afternoon when I'm back at my desk.

**Comment by lwm** [comment]
Done!

https://pypi.python.org/pypi/oic/0.9.5.0
