### ISSUE TITLE
Trouble running op2

### ISSUE THREAD

**Issue by murkuro** [OpenIDC/pyoidc#271]
I am building the project on ubuntu 16.04. I have run the python setup.py install in virtual environment using python3.5 and also used pip3 to install requirements.txt in simple_op and simple_rp. When I run ./start.sh in op2 I get the messaged 
```
_File "./server.py", line 10, in <module>
    from oic.utils import shelve_wrapper
  File "/home/hinrik/OpenIDConnect/pyoidc/venv/lib/python3.5/site-packages/oic/utils/shelve_wrapper.py", line 2, in <module>
    import anydbm
ImportError: No module named 'anydbm'_
```
When I googled anydbm I found it was blacklisted and am having a hard time installing it. Should anydbm be installed or am I doing something wrong??

**Comment by lwm** [comment]
Hi @murkuro, unfortunately, no one can get any of the examples working right. They've gone unmaintained. We're going to be working on improving this ASAP. Please see https://github.com/rohe/pyoidc/issues/254 for more background on this.

**Comment by VJalili** [comment]
I simplified op2 in op3, and it works fine on my side.
I'm running python 2.7.10

Regarding your issue; it seems it's not pyoidc problem, rather it's python interpreter. 
Googling I got this: 


> To fix this error change a default interpreter from /usr/bin/apt-listchanges to Python 2. First, check available python versions on your system:
> ```
> # ls /usr/bin/python*
> /usr/bin/python  /usr/bin/python2  /usr/bin/python2.7  /usr/bin/python3  /usr/bin/python3.4  /usr/bin/python3.4m  /usr/bin/python3m
> ```
> Next, change a fist line of /usr/bin/apt-listchanges script:
> ```
> FROM:
> #!/usr/bin/python
> TO:
> #!/usr/bin/python2.7
> ```

source: https://linuxconfig.org/importerror-no-module-named-anydbm-on-debian-linux-solution

**Comment by lwm** [comment]
> I simplified op2 in op3, and it works fine on my side.

Can you please share this code!? Thanks!

**Comment by VJalili** [comment]
sure, it's already merged :)
https://github.com/OpenIDC/pyoidc/tree/master/oidc_example/op3

**Comment by lwm** [comment]
> sure, it's already merged :)

Awesome!

Closing this one off in light of https://github.com/OpenIDC/pyoidc/issues/271#issuecomment-298711448. @murkuro, please re-open if your issue persists and we need to do more here. Thanks!
