### ISSUE TITLE
Unable to install from source

### ISSUE THREAD

**Issue by KyleBrownCS** [OpenIDC/pyoidc#275]
Latest commit(s?) cause `python setup.py install` to fail. 

Output

> running install
> Checking .pth file support in /Library/Python/2.7/site-packages/
> /usr/bin/python -E -c pass
> TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
> running bdist_egg
> running egg_info
> creating src/oic.egg-info
> writing requirements to src/oic.egg-info/requires.txt
> writing src/oic.egg-info/PKG-INFO
> writing top-level names to src/oic.egg-info/top_level.txt
> writing dependency_links to src/oic.egg-info/dependency_links.txt
> writing manifest file 'src/oic.egg-info/SOURCES.txt'
> error: package directory 'src/oic/federation' does not exist

I reverted to 4b7df5ba6d27e8c162281e27e33109e9470dfb58 and it ran successfully. I haven't tried any other versions.

Edit: I realize I should have used the latest release to ensure everything worked. Sorry about that

**Comment by lwm** [comment]
Sorry @KyleBrownCS, this indeed was a problem that was created by https://github.com/OpenIDC/pyoidc/commit/4a3558da3e6575e6a20106016dad4d018007163a (\cc @rohe). I've solved that issue with https://github.com/OpenIDC/pyoidc/pull/277 (awaiting merge). Glad you could get moving again pretty fast.

Re-opening until #277 goes into master.

**Comment by rohe** [comment]
I think all the problems with removing the federation code is now solved.

**Comment by lwm** [comment]
Thanks!
