### ISSUE TITLE
oauth2 provider redirect_uris iteration

### ISSUE THREAD

**Issue by niyue** [OpenIDC/pyoidc#283]
I tried to get `oidc_example/simple_op` up and running, and ran into one issue. When verifying the redirect URI, the provider reported some error:
```
ValueError: need more than 1 value to unpack
```

I checked out the code, and found this piece of code when verifying redirect URI in 
https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oauth2/provider.py#L231-L232:
```
for regbase, rquery in self.cdb[str(areq["client_id"])][
                "redirect_uris"]:
```

It seems `self.cdb[str(areq["client_id"])]["redirect_uris"]` is a dictionary and we are trying to iterate this dictionary and unpack the dictionary item into key (`regbase`) and value (`rquery`).  However, we have to call `items()` [when iterating a dictionary](http://stackoverflow.com/questions/3294889/iterating-over-dictionaries-using-for-loops-in-python), otherwise, we will run into issue like above.

I am not sure if I miss something but I have to modify the source code to append `items()` to get it fixed:
```
for regbase, rquery in self.cdb[str(areq["client_id"])][
                "redirect_uris"].items():
```

Could you confirm if it is a bug or there is something I got wrong? Thanks.

I am using [Python 2.7.13 in Docker's official Python image](https://hub.docker.com/_/python/).

**Comment by lwm** [comment]
Hi @niyue, unfortunately, the examples are a big black box for us right now and we have not been able to get the hours free to resolve the many issues we've seen reported. If your proposed changes were able to help you make something work, please consider submitting them in a pull request :beers:

**Comment by niyue** [comment]
@lwm PR submitted, please have a look, thanks.

**Comment by tpazderka** [comment]
I think that this issue is not valid as it looks like a misunderstanding of the structure required in `redirect_uris`.
