### ISSUE TITLE
Values of 'OAS.userinfo'

### ISSUE THREAD

**Issue by VJalili** [OpenIDC/pyoidc#289]
I'm trying to understand op2 example. 
We have: 

```
if config.USERINFO == "SIMPLE":
        OAS.userinfo = UserInfo(config.USERDB)
    elif config.USERINFO == "SAML":
        OAS.userinfo = UserInfo(config.SAML)
    elif config.USERINFO == "AA":
        OAS.userinfo = AaUserInfo(config.SP_CONFIG, _issuer, config.SAML)
    else:
        raise Exception("Unsupported userinfo source")

```

What if my user info are stored on a database (e.g., postgres, or SQL server) ?!

**Comment by lwm** [comment]
Hi @VJalili, bearing in mind we are [facing many example issues](https://github.com/OpenIDC/pyoidc/issues?q=is%3Aopen+is%3Aissue+label%3Aexamples) and they are quite unmaintained, the example configuration is a dictionary but there is no restriction on you using postgres/SQL. The example simply does not cover that.

**Comment by VJalili** [comment]
Could you please provide a short example on how to connect a postgres table to `OAS.userinfo`? 

Given that the postgres/SQL table containing user info could potentially be very large, I prefer that pyoidc queries the database instead of passing the info of the table to pyoidc.

**Comment by lwm** [comment]
> Could you please provide a short example on how to connect a postgres table to OAS.userinfo?

I'm sorry, I just don't have time to dig into this. We're snowed under with maintenance issues right now. If you get something working please do consider sharing it with us.

**Comment by rohe** [comment]
The class instance at OAS.userinfo must adhere to the pattern spelled out in src/oic/utils/userinfo/__init__.py .
I have not seen any implementation of a postgres/SQL version of UserInfo.
This doesn't mean there isn't one :-/
