### ISSUE TITLE
Using static code control in CI - isort

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#297]
It might be a good practice to use an static checks of the code. One of the first (and probably easiest steps) would be to add an automated sorting of imports (and incorporate such checks in CI to enforce them).

One of the best tools available is [isort](https://pypi.python.org/pypi/isort) which allows for sorting as well as for checking.
I would also recommend to convert to a more compact style of imports (`2 - Hanging Indent` perhaps).

If you agree then I can take care of this.

**Comment by lwm** [comment]
Yes, I agree!

I've also created https://github.com/OpenIDC/pyoidc/issues/298, inspired from this.

I'd suggest running it from the Makefile with a target like:

```makefile
isort:
	find src/ tests/ -name "*.py" | xargs isort -c
.PHONY: isort
```

It would fail when it finds a badly sorted import list. You could call it in the `.travis.yml` then.

I would also add a new `quality.in` to the requirements folder with the isort dependency. Add that new file to `ALL_REQS` (in the Makefile) and then you can run `make upgrade ` to generate the `quality.txt` pinned dependencies.

**Comment by rohe** [comment]
@tpazderka I also support you proposal

**Comment by tpazderka** [comment]
OK then, I will look into it and submitt a PR.

@rohe if you like one import per line, then we can go with style `1 - Vertical`.

@lwm I was going to propose `flake8` as another step :) I do not have any experience with `pylama` but we do use `flake8` so it would be a logical choice for me.

**Comment by lwm** [comment]
Nice to see some agreement here :)

> I do not have any experience with pylama but we do use flake8 so it would be a logical choice for me.

Flake8 is just a wrapper for pyflakes, mccabe and pycodestyle. pylama is a wrapper for those **and** pydocstyle, pylint and radon. So it's the same but more :)
