### ISSUE TITLE
Fix dependency building with Tox and Travis

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#301]
Follows from https://github.com/OpenIDC/pyoidc/pull/299#discussion_r108137709.

**Comment by tpazderka** [comment]
It looks like `tox` always pulls dependencies and it installs `pyoidc` from pip and not from repository...

I don't have enough experience with Travis and/or Tox.

@lwm Could you please advise?

**Comment by lwm** [comment]
I'll give it a shot over at #302 and let's see how it goes!
