### ISSUE TITLE
error_to_catch doesn't work

### ISSUE THREAD

**Issue by rohe** [OpenIDC/pyoidc#313]
I get the following exception:

```
File "/usr/local/lib/python3.5/dist-packages/oic-0.10.0.0-py3.5.egg/oic/utils/keyio.py", line 1037, in build_keyjar
    except error_to_catch:
TypeError: catching classes that do not inherit from BaseException is not allowed

error_to_catch = getattr(__builtins__, 'FileNotFoundError', 'IOError')
```

a couple of lines before.

Not sure who added this but please fix.

**Comment by rohe** [comment]
I've used this a a quick fix

                try:
                    error_to_catch = FileNotFoundError
                except NameError:
                    error_to_catch = IOError 

Works both for 2.7 and 3.5

**Comment by tpazderka** [comment]
`FileNotFoundError` is a subclass of `BaseException` in python 3.5.

https://docs.python.org/3.5/library/exceptions.html#FileNotFoundError

**Comment by rohe** [comment]
Ah, well! Just telling you what I got.

**Comment by tpazderka** [comment]
Yeah, there was a bug...
Fix is in the referenced commit, I will add a test and then create PR.
