### ISSUE TITLE
Wrong release tag

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#316]
The `0.10` release is tagged as `10.0`

**Comment by lwm** [comment]
Oh, I'll fix that. For a second I thought I made the wrong release on pypi ...

**Comment by lwm** [comment]
https://github.com/OpenIDC/pyoidc/releases/tag/v0.10.0

However, git and github seem to not think this is the latest?

**Comment by tpazderka** [comment]
Thanks! I am not sure how this thing about releases work...

**Comment by lwm** [comment]
I think it is because we are prefixing the tag with the character 'v'? I am not sure but I will close this off now as the latest tag follows the correct bump. :+1:

**Comment by tpazderka** [comment]
No, I think you have to add [release notes](https://github.com/OpenIDC/pyoidc/releases/new?tag=v0.10.0)

**Comment by lwm** [comment]
Oh, that is strange but you're right! Thanks!

https://github.com/OpenIDC/pyoidc/releases/tag/v0.10.0
