### ISSUE TITLE
what is `symkey` and where it is used?

### ISSUE THREAD

**Issue by VJalili** [OpenIDC/pyoidc#322]
The `Provider` class (@ /pyoidc/src/oic/oauth2/provider.py`) is initialized with a parameter called `symkey`.  This parameter is used to initialize a local parameter of the same name `self.symkey = symkey`.

But it seems `self.symkey` is never used. Am I missing something?

**Comment by rohe** [comment]
It's used in a special type of user authentication.
SymKeyAuthn in src/oic/utils/user.py
We had a use case very early on.

**Comment by lwm** [comment]
Hmmmm, `symkey` is not an optional parameter. I think we should make it optional.

**Comment by rohe** [comment]
Agree

**Comment by VJalili** [comment]
It is optional: `symkey="" `
I'm using `UserPassword` authentication, and I was wondering what is `SYM_KEY = "SoLittleTime,Got"` in the configuration. 
It's good to know that it's just used in `SymKeyAuthn`.

**Comment by lwm** [comment]
> It is optional: symkey=""

Not for `oic.oic.Provider`. I'll submit a pull request.
