### ISSUE TITLE
Remove defaults for security related settings

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#326]
Some classes have security related settings as optional arguments with defined value or do define such value if `None` is provided. This is considered as a bad practice and either they should not be optional where it makes sense or should raise `ImproperlyConfiugured` if user tries to use them without providing a value.

**Comment by lwm** [comment]
Sounds sensible!

**Comment by schlenk** [comment]
At least:

- [ ] utils/sdb.py SessionDB `password` and `secret`

I don't think examples should matter in this case, if the secrets are in the configuration part.
