### ISSUE TITLE
Allow for absolute URL in Endpoint class

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#327]
`Endpoint` class now allows only for relative path for the endpoint location respective to `baseurl`.

It might be desirable to allow for full paths to be configurable as well.

Changes to the `Endpoint` class:
```python
class Endpoint(object):
    full_url = None

    def get_url(self, base_url):
        returns full_url if defined, otherwise urljoins base_url with url
``` 

This should retain the current behavior but allows for different configurations.

**Comment by lwm** [comment]
Sounds fine by me.

**Comment by tpazderka** [comment]
OK, it might not be **that** usefull as I initially thought but I will add it anyway...

**Comment by lwm** [comment]
Well, you had the initial use case idea. If that is not as appealing now and no one else has asked for this, then I don't see why we would add? I'm happier to delete code than add it :)

**Comment by tpazderka** [comment]
Yeah, you are probably right...
