### ISSUE TITLE
 AttributeError: 'DefaultToken' object has no attribute 'info'

### ISSUE THREAD

**Issue by madjoks** [OpenIDC/pyoidc#333]
Hello, i'm want to use oic/extension/provider.
So I create subclass MyOIDCProvider nested from oic/oic/provider/Provider and oic/extension/provider/Provider

When I call intospenction endpoint I receive the exception :
oic\extension\provider.py", line 835, in get_token_info
    _info = self.sdb.token_factory['access_token'].info(
AttributeError: 'DefaultToken' object has no attribute 'info'

Then I looked in the test_x_provider.py and use JWTToken, but he haven't info method too.
What am I doing wrong? Maybe there's misspelling - info->get_info ?

**Comment by lwm** [comment]
> So I create subclass MyOIDCProvider nested from oic/oic/provider/Provider and oic/extension/provider/Provider

I think it is better to only subclass a single Provider parent class. Unless you have some special need from reading the implementation of oic.extension.provider.Provider, I would stick with using oic.oic.provider.Provider.

**Comment by madjoks** [comment]
Well I actually ment that it seems there's a bug in oic/extension/provider/Provider: it uses method "info" of a token But neither DefaultToken nor JWTToken is really implement it.
So I'd like to know if it really a bug or am I missed something?

**Comment by rohe** [comment]
I think it's a 'spelling' error. Should be .get_info() instead of .info() .

Also note that whatever is in oic/extension should be regarded as experimental because it's implementations of things-to-be/nice-things-to-have rather then fixed standards.

**Comment by tpazderka** [comment]
This has been fixed on master.
