### ISSUE TITLE
Improve form_post capabilities

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#334]
Current support for `form_post` method uses predefined template and does not allow for its substitution and redefinition.

The predefined form itself contains an invalid HTML (missing `"` around `action`) and contains inline JS which is not allowed in Content Security Policy.

The included form should be a valid HTML and should not contain inline JS in order to be usable on sites with CSP enabled.

It should also be possible to replace the form with a custom one.

**Comment by rohe** [comment]
No one would be happier then me if we could get rid of the inline JS.
When I did this a couple of years back there wasn't any alternative.
If there is one today it would make my day.

**Comment by tpazderka** [comment]
I will fix the HTML to make it valid and an option to override the default form with a custom one.

It is probably unrealistic to try to fix the inline JS in the default one. But this should be good enough.
