### ISSUE TITLE
How username/password is sent to `verify` endpoint

### ISSUE THREAD

**Issue by VJalili** [OpenIDC/pyoidc#336]
One of the many endpoints of OpenID Connect is `verify`, which is reached when the user has entered username and password. This is how we create the `verify` endpoint: 

`_urls.append((r'^' + endPoint, make_auth_verify(authnIndexedEndPointWrapper.verify)))` 
[ref](https://github.com/OpenIDC/pyoidc/blob/master/oidc_example/op3/server.py#L456)

We access this endpoint as follows: 
```
for regex, callback in self.urls:
    match = re.search(regex, path)
    if match is not None:
        try:
            environ['oic.url_args'] = match.groups()[0]
        except IndexError:
            environ['oic.url_args'] = path
        try:
            return callback(environ, start_response)
        except Exception as err:
            print("%s" % err)
            message = traceback.format_exception(*sys.exc_info())
            print(message)
            logger.exception("%s" % err)
            resp = ServiceError("%s" % err)
            return resp(environ, start_response)
```

My question is: I don't understand how you pass the entered username and password to the `verify` endpoint.

**Comment by lwm** [comment]
> how you pass the entered username and password to the verify endpoint.

I am not sure if there is a difference between the various OpenID Connect flows (authorization, implicit, hybrid) but here is how I made it work for the authorization flow:

1) An initial HTTP GET request is passed to `provider.authorization_endpoint` (this is the result of the initial redirect from the frontend, then conducted by the user agent to the provider. The first step.).
2) A HTML form is returned in the response (from your `authn.__call__` function) which will be the login form the user agent handles.
3) In this form, the username and password fields are present. You will usually need to carry through the state of the query parameters from the initial request (usually with a hidden input in the form) for the server side to handle in the submission.
4) This form submits via HTTP POST the username and password, and you point it to the end-point that has your `provider.verify` handler.

There are many ways to do this but that is a rough outline. The specification is quite open ...

**Comment by VJalili** [comment]
Could you elaborate ? 

How is your description related to the following class? 

```
class AuthnIndexedEndpointWrapper(UserAuthnMethod):
    def verify(self, **kwargs):
        return self.authn_instance.verify(end_point_index=self.end_point_index, **kwargs)
```
This is how my `kwargs` look like: 
`kwargs:  {'query': u'nonce=qw2ybMgK0Fmvpk8b8M8BlyHHoYIbF7c9&acr_values=SAML&state=8yBGiQpLjbNxAUdxLKUvzrWF5PSc4nbt&redirect_uri=http%3A%2F%2Flocalhost%3A8040%2Fauthz_cb&response_type=code&client_id=QIy0DBApm2hy&scope=openid+profile+email+address+phone', 'login': u'user1', 'password': u'1', 'form.commit': u'Submit', 'acr_values': u"[u'SAML']"}`

I'm expecting this `kwargs` to be sent to the `verify` endpoint.

**Comment by lwm** [comment]
> How is your description related to the following class? 
> 
> ```
> class AuthnIndexedEndpointWrapper(UserAuthnMethod):
>     def verify(self, **kwargs):
>         return self.authn_instance.verify(end_point_index=self.end_point_index, **kwargs)
> ```

That was part 3 of my description above.

> This is how my `kwargs` look like: 
> `kwargs:  {'query': u'nonce=qw2ybMgK0Fmvpk8b8M8BlyHHoYIbF7c9&acr_values=SAML&state=8yBGiQpLjbNxAUdxLKUvzrWF5PSc4nbt&redirect_uri=http%3A%2F%2Flocalhost%3A8040%2Fauthz_cb&response_type=code&client_id=QIy0DBApm2hy&scope=openid+profile+email+address+phone', 'login': u'user1', 'password': u'1', 'form.commit': u'Submit', 'acr_values': u"[u'SAML']"}`
> 
> I'm expecting this `kwargs` to be sent to the `verify` endpoint. 

Ah, but you've already managed to receive the username/password here. All the `oic.provider.Provider.verify_endpoint` does is validate the payload and run `UserAuthnMethod.verify`. You're already doing this.

You may be confusing `UserAuthnMethod.verify` and `oic.provider.Provider.verify_endpoint`?

**Comment by VJalili** [comment]
Please elaborate the differences between `UserAuthnMethod.verify` and `oic.provider.Provider.verify_endpoint`, and which one should receive the aforementioned `kwargs`

**Comment by lwm** [comment]
> UserAuthnMethod.verify

The function that does the actual authentication. 

> oic.provider.Provider.verify_endpoint

The end-point that receives the request and passes everything to `UserAuthnMethod.verify`.

**Comment by VJalili** [comment]
Let's read my original question one more time, and try to answer it using your comments. 

- `verify` endpoint is defined (not `verify_endpoint`) as: 
`_urls.append((r'^' + endPoint, make_auth_verify(authnIndexedEndPointWrapper.verify)))`
- when a relying party reaches the `verify` endpoint, the provider returns:
`make_auth_verify(authnIndexedEndPointWrapper.verify)`

My question is: I don't see how the `verify` endpoint receives the entered username and password. 

Referring to _op2/op3_ examples; I don't see `verify_endpoint` but I see `verify` endpoint, and it's not clear how you pass the entered username and password to it.

**Comment by VJalili** [comment]
To be precise; I have following code (wrapping to WSGI server is done at different layers which I don't need to touch here): 

```
    @web.expose
    def verify(self, trans, **kwargs):
        print 'provider.authn_broker: ', self.provider.authn_broker
        print 'kwargs: ', kwargs
        return self.provider.verify_endpoint()
```
The output is: 
```
provider.authn_broker:  <oic.utils.authn.authn_context.AuthnBroker object at 0x11124dc10>
kwargs:  {'query': u'nonce=mBKYt7IDKhd5j2fSUt0n0sO778WgTw9t&acr_values=SAML&state=8CEdxqsLLDWiaRSAVzu3Z7wFEZzTAkcU&redirect_uri=http%3A%2F%2Flocalhost%3A8040%2Fauthz_cb&response_type=code&client_id=k7MVNlcZa5Df&scope=openid+profile+email+address+phone', 'login': u'user1', 'password': u'1', 'form.commit': u'Submit', 'acr_values': u"[u'SAML']"}
```
This way I always get `false` as user verification. The `kwargs` has the entered username and password, but if I pass `kwargs` to the `request` argument as: 
`return self.provider.verify_endpoint(request=kwargs)`
I get following error: 
`AttributeError: 'NoneType' object has no attribute 'verify'`

**Comment by lwm** [comment]
> if I pass kwargs to the request argument as: 
> ``` python
> return self.provider.verify_endpoint(request=kwargs)
> ```
> I get following error: 
> ``` python
> AttributeError: 'NoneType' object has no attribute 'verify'
> ```

If you're using `oic.oic.provider.Provider` (you should be!), then it is probably because of [this section of the verify_endpoint code](https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oic/provider.py#L649-L655). Use a debugger statement to make sure that:

``` python
authn, acr = self.pick_auth(areq, "exact")
```

Is returning something for you.

**Comment by lwm** [comment]
Regarding your initial question, I have outlined the entire process in https://github.com/OpenIDC/pyoidc/issues/336#issuecomment-297083784. With my latest comment I have addressed another issue altogether. Please open another issue if you want to address individual stack traces. I hope this is making sense.

**Comment by VJalili** [comment]
I traced the error to the following line: 
[_refs = self.db["key"][acr]](https://github.com/OpenIDC/pyoidc/blob/master/src/oic/utils/authn/authn_context.py#L100)

My values are: 
```
acr:  SAML
comparison type:  exact
self.db:   {'info': {'1': {'authn_auth': '', 'ref': 'PASSWORD', 'method': <oic.utils.authn.multi_auth.AuthnIndexedEndpointWrapper object at 0x1174e6e10>, 'level': 1}}, 'key': {'PASSWORD': ['1']}}
```
The returned value is: `[]`, which is the cause of the error. 

Any suggestion?

**Comment by lwm** [comment]
You might be missing this configuration step:

``` python
def configure_auth_broker(provider):
    authn_broker = AuthnBroker()
    authn_broker.add("LDAP", LDAPAuth(provider))
    provider.authn_broker = authn_broker
```

Where yours would involve something with SAML.

**Comment by VJalili** [comment]
I "think" the problem is solved by making following change in my relying party: 
From: `ACR_VALUES = ["SAML"]`
To: `ACR_VALUES = ["PASSWORD"]`

I setup the providers `AuthBroker` is following: 
```
authnBroker = AuthnBroker()
authnBroker.add(
    oidcConfig.AUTHENTICATION["UserPassword"]["ACR"],  
    self.authnIndexedEndPointWrapper,
    oidcConfig.AUTHENTICATION["UserPassword"]["WEIGHT"],
    "") 
```
Do I need to add `LDAP` too?

**Comment by lwm** [comment]
> Do I need to add LDAP too?

If you're using LDAP authentication, then yes, if not, then no.

**Comment by VJalili** [comment]
No, I'm not using.

**Comment by lwm** [comment]
You're welcome.
