### ISSUE TITLE
How to ask a provider to issue a `Client ID`?

### ISSUE THREAD

**Issue by VJalili** [OpenIDC/pyoidc#340]
An ID token issued by a provider, has a required `aud` field, which is the OAuth2.0 `client_id` of the audience(s) to whom the ID token is issued for. A provider keeps track of all authenticated `cliend_id`s in a database (e.g., see [this line](https://github.com/OpenIDC/pyoidc/blob/master/oidc_example/op3/server.py#L374)).

The question is: where do you get client IDs from a provider? I'm expecting an endpoint in the provider where a request to register an audience (i.e., a relying party) is sent-to. For instance, [this](https://developers.google.com/identity/sign-in/web/devconsole-project) and [this](https://developers.google.com/fit/android/get-api-key) is how you obtain a `client_id` for a relying party from google. However, I don't see such an endpoint; and all I read is hardcoded client ID's for the relying parties (e.g., [this](https://github.com/OpenIDC/pyoidc/blob/master/oidc_example/rp2/oidc.py#L39), and [this](https://github.com/OpenIDC/pyoidc/blob/master/oidc_example/rp3/conf.py.example#L55))

Anyone knows how an audience can obtain a `client_id` from the provider?

**Comment by lwm** [comment]
@rohe, does `oic` provide [dynamic client registration](https://openid.net/specs/openid-connect-registration-1_0.html)?

**Comment by tpazderka** [comment]
Yes, it does provide a [registration_endpoint](https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oic/provider.py#L1608).

**Comment by rohe** [comment]
So, it does!
I wrote a script some time ago for supporting static client registration (actually it's a client info management script) should probably add that to the distribution.

**Comment by VJalili** [comment]
@rohe & @lwm could we add a support to static client registration? 
meanwhile, @rohe , could you plz share the script you wrote for the static client registration?

**Comment by lwm** [comment]
> static client registration? 

It is already supported. You mean dynamic?

**Comment by VJalili** [comment]
No, I actually mean static client registration.

**Comment by lwm** [comment]
Static client registration just means setting variables on both the provider and client side that match, as far as I understood. @rohe, are you referring to something more or?

**Comment by schlenk** [comment]
Probably this helps: https://github.com/OpenIDC/pyoidc/blob/master/src/oic/utils/client_management.py

Its a command line tool to register a client.

**Comment by VJalili** [comment]
@schlenk Thank you.
