### ISSUE TITLE
oic.utils.authn.user.BasicAuthn.verify_password should use constant time check

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#341]
The verify password method uses a naive == comparision for password strings, which allows timing attacks.

It should use a constant time comparision.

As it is a dependency anyway, maybe use:
cryptography.hazmat.primitives.constant_time.bytes_eq

https://cryptography.io/en/latest/hazmat/primitives/constant-time/

**Comment by lwm** [comment]
Fair point. Would appreciate a PR @schlenk! You seem to know what you're talking about :smile:

**Comment by schlenk** [comment]
Thinking about it. It should probably not do the password handling itself at all but use a decent library like [passlib](https://pypi.python.org/pypi/passlib) to handle encrypted password storage and comparision. 

At least if the code is more than a glorified example.

**Comment by lwm** [comment]
I'd be OK with adding this `passlib` dependency! Go for it :+1:
