### ISSUE TITLE
Provider.create_providerinfo uses os.path.join() to join URLs, which breaks on Windows

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#344]
This breaks:

            _provider_info['{}_endpoint'.format(endp.etype)] = os.path.join(
                self.baseurl,
                endp.url)

If platform is Windows, os.sep == '\\' and the URLs will be wrong.

This should simply use urljoin().

**Comment by lwm** [comment]
Nice one! :+1:
