### ISSUE TITLE
Using an issuer with a path component produces invalid openid-configuration URLs

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#346]
Assume an issuer retrieved via Client.discovery() contains a path component (which seems legal from my reading of section 3 of the Open ID Connect Discovery 1.0 spec, which forbids fragments and query parts but not path elements in the issuer):
e.g. 

    issuer = 'https://example.com/oidc/'
    pinfo = client.provider_config(issuer)

=> Error, the URL requested is 'https://example.com/oidc/.well-known/openid-configuration'

I think it should be https://example.com/.well-known/openid-configuration at least according to RFC 5785 all the `/.well-known` URLs start at the top level.

The problem is the naive url construction in `provider_config`, which should probably be done like this instead:

    _authority = "{0.scheme}://{0.netloc}".format(urlparse(_issuer))
    url = serv_pattern % _authority

**Comment by rohe** [comment]
You're right! Please issue a PR.

**Comment by schlenk** [comment]
Seems some others also produce RFC violating .well-known links 

Microsoft Azure for example generates this: 
`https://login.microsoftonline.com/{tenant}/.well-known/openid-configuration` 

[https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-openid-connect-code](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-openid-connect-code)

so probably this should be an option where exactly to place those links.

**Comment by tpazderka** [comment]
I think, we should conform with the RFC. I am for merging the #347.

**Comment by rohe** [comment]
I remember having a discussion about this and I got to the same conclusion as https://github.com/tpazderka.

RFC5785 says the path component begins with /.well-known/
On the other hand http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig says RFC5785 applies if the issuer ID has _no_ path component. Implicitly stating that /.well-known/ may not be at the beginning of the path component if the issuer ID contains a path which it's allowed to do.

So given the example given by https://github.com/schlenk the resulting URL should be:
https://example.com/oidc/.well-known/openid-configuration

Which makes it reasonable to do what https://github.com/tpazderka suggests.

**Comment by schlenk** [comment]
Agreed. 

I missed the explicit statement in the openid-connect-discovery spec.

The discovery client should probably check both and the server side should announce the issurer/.well-known version.
