### ISSUE TITLE
unicode problem with python 2

### ISSUE THREAD

**Issue by rajeceind** [OpenIDC/pyoidc#348]
In pyoidc library, line number **490** of **oic/utils/authn/client.py**,  **_id** retrieved is of type Unicode so it throws error in python 2.7 as 

> str required for key but unicode found. 

Encode it to ascii 
 _id.encode('ascii')

**Comment by lwm** [comment]
Hi @rajeceind, thanks for the report! Could you submit a fix for this?

**Comment by tpazderka** [comment]
Python 2 is no longer supported.
