### ISSUE TITLE
oic.utils.sdb.Crypt uses a weak key derivation function and constant IV

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#349]
The oid.utils.sdb.Crypt function code uses a single round of sha256 as a rather weak KDF.

Additionally it uses a constant Initialization Vector for AES.CBC which is also not a great idea.
(see for example http://cwe.mitre.org/data/definitions/329.html  and for a more visual explanation of the attack, see http://stackoverflow.com/questions/3008139/why-is-using-a-non-random-iv-with-cbc-mode-a-vulnerability ).

Well even using CBC mode is not a good idea anymore. Should be some form of AEAD (like AES-GCM, or similar).

**Comment by tpazderka** [comment]
Thank you for your suggestion. Could you please submit a PR?

**Comment by Victor-Savu** [comment]
Is this issue resolved now? Can it be closed?

**Comment by schlenk** [comment]
This is mostly fixed, yes. The only part remaining is the weak KDF, but thats actually more a bad naming for the 'password' parameter, which should not be a password (needing a KDF to add entropy) but should simply be a high entropy key already.
So yes, okay to close.

**Comment by lwm** [comment]
> but thats actually more a bad naming for the 'password' parameter, which should not be a password (needing a KDF to add entropy) but should simply be a high entropy key already.

If you feel like this should change, please open an issue. All breaking changes considered ;)

> So yes, okay to close.

Closing then :beers:
