### ISSUE TITLE
Has anyone used pyoidc behind nginx ?

### ISSUE THREAD

**Issue by VJalili** [OpenIDC/pyoidc#350]
I'm hosting an identity provider behind a nginx. A first step for a relying party would be accessing some end points such as `/.well-known/openid-configuration`. But it seems nginx is redirects all requests to `*/.well-known/*` addresses to a root path `/usr/local/nginx/html` or `/usr/share/nginx/html/` that tries to access `/usr/share/nginx/html/oidc/.well-known/openid-configuration` -- which obviously does not exist -- and throws 404.

I have tried solutions such as adding following to `nginx.conf`: 
`location ~ ^/.well-known/* { allow all; }`

but no joy yet. Its clear that this is an issue setting up `nginx` not a `pyoidc` problem, but I was wondering maybe someone has tried `nginx+pyoidc` combination before that can hint me.

**Comment by schlenk** [comment]
Probably just add a proper alias:

    location /.well-known/openid-configuration {
         alias /oidc/.well-known/openid-configuration;
    }

**Comment by VJalili** [comment]
I tried that, it throws 403: 

``(13: Permission denied), client: 137.53.241.62, server: localhost, request: "GET /oidc/.well-known/openid-configuration HTTP/1.1", host: "34.192.55.50"``

**Comment by VJalili** [comment]
The problem is with the `location ~ ^/.well-known/* { allow all; }`. Remove it from any of the configuration files, then you're good to go.
