### ISSUE TITLE
Interface between oic.utils.sdb.SessionDB and the db parameter lacks a bit

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#355]
I'm trying to write a simple Redis backend for session storage, to plug into the 'db' argument of the SessionDB constructor.

When trying it, it works mostly okay, but requires some ugly hacks, to serialize the stored data.

One example is `create_authz_session` which stores a variety of data in the session db. Most is stringified or at least a primitive type like a list, so it can be simply handed to `json.dumps` and all is nice. The code even tries to make it easier by explicitly stringifying some parameters by explictit to_json calls. But this misses the `authn_event` class, so the serializer in the db backend need special knowledge to serialize it again.

For example, when logging the arguments of the __setitem__ call:

>   Setting Session [c09395736652cbeee36e7af7c34baf1f21ffb35c87eb39f26521e069] with values: {'nonce': 'LTWXRpP38dhYvIiE', 'code': u'r5Wj3lt4XA0FnCUka5k/z4GsP7+79r77hX+JIbMdmdZbgwb7dkvbslhH4mbg+LupyB0lc5xvVcw/chD0B6Y/Vuw5t9EMcD9J/+0dhq/oIK83TnlucVTdGsY+KTsGif2fOdVD8p6VOnsrQIfXuTI4WA==', 'authzreq': '{"nonce": "LTWXRpP38dhYvIiE", "prompt": ["consent"], "state": "3WrprivtTVfKkLcx", "redirect_uri": "https://oidc.example.org:8443/ologin", "response_type": "code", "client_id": "qah5LHIg1Aqa", "upm_answer": "true", "scope": "openid profile offline_access"}', 'authn_event': <oic.utils.sdb.AuthnEvent object at 0x196EE0B0>, 'response_type': ['code'], 'client_id': 'qah5LHIg1Aqa', 'oauth_state': 'authz', 'revoked': False, 'state': '3WrprivtTVfKkLcx', 'redirect_uri': 'https://oidc.example.org:8443/ologin', 'code_used': False, 'scope': ['openid', 'profile', 'offline_access']}

nicely serializable, only the `authn_event` parameter makes troubles.

Probably just missing an implementation of to_json()/from_json() and a call for the authn_event part.

**Comment by lwm** [comment]
> but requires some ugly hacks, to serialize the stored data.

Yep! I wrote this [RedisSessionDB](https://gitlab.com/fsfe/oidcp/blob/master/oidcp/session.py#L33) and came across this.  I pickle the payload to avoid the missing `authn_event` serialization. In this case, the pickling is fine because the server controls what goes in ... but it's a hack alright.

> But this misses the authn_event class

If this is an issue primarily about correctly serializing the `authn_event`? Or you'd like to suggest deeper improvements in relation to implementing a Redis back-end? To be honest, I think we should provide a default Redis implementation for the underlying SessionDB.db.

**Comment by schlenk** [comment]
@lwm Nice, will have a look. I went with JSON and a custom serializer that takes care of the authn_event for now, because pickles tend to have security and other issues, especially when classes change.

I think my main issue with the interface is, is that it is unclear what the interface really is. It is quite underspecified what contracts and promises the SessionDB follows.

Just to list a few unspecified things:

- Are modifications done in a sane way, so setitem is always triggered?
  For example take the 'scope' key of the above example, its value is a list, so it is mutable. Simply doing a
  dict like object would miss mutations of that value, as the \_\_setitem\_\_ code would never be called.
- Are the values always trivially serializable (e.g. integers, bytes, strings, dicts, lists, tuples)?
  No bad surprises like generator expressions, circular structures, random class instances or similar
  nasty stuff.
- Is access done in a sane way, so getitem can be implemented efficiently?
  So fetching values once and not hitting getitem over and over again with the same key, which forces
  intelligent caching due to bad access patterns.
- Which dict methods need to be available?

So i think the db argument should have some class prototype too, just like the refresh_db and not be a naked dict, this would help to make it clear what the interface actually is, because generic dict is a bit broad for a persistance layer.

It would also help to document, what is actually stored/fetched. My first attempt was tripped by TypeErrors when access happend with an integer key instead of a string i would have expected from cursory reading of the code.

**Comment by lwm** [comment]
> So i think the db argument should have some class prototype too, just like the refresh_db and not be a naked dict, this would help to make it clear what the interface actually is, because generic dict is a bit broad for a persistance layer.

Yes, a good first step. After this, we could move to specific back-end interfaces (redis, mysql, etc.).

> It would also help to document, what is actually stored/fetched. 

Agreed! The documentation issue is only growing ... ;)

**Comment by lwm** [comment]
So, to move along with this, I've created https://github.com/OpenIDC/pyoidc/issues/360. If you can break the discussion here up into actionable issues, we can get going there too! Otherwise, I would close this one off.

**Comment by schlenk** [comment]
Ok. Guess the other actionable item is 'provide a base class documenting the interface'.
