### ISSUE TITLE
Consider changing the pypi url to reflect git fork strategy

### ISSUE THREAD

**Issue by gene1wood** [OpenIDC/pyoidc#356]
I'm not entirely clear what the intent is with the following (and have heard from two other developers that use pyoidc that they have the same question/confusion)

What is the relationship between https://github.com/OpenIDC/pyoidc and https://github.com/rohe/pyoidc ?

It appears that `OpenIDC/pyoidc` is the parent and `rohe/pyoidc` is the child in the fork relationship based on GitHub's annotations.

The pypi module however lists the child as the [URL of the project](https://github.com/OpenIDC/pyoidc/blob/300adc8cdf1670f6c41dd28394958162ab5a213a/setup.py#L58). Is this intentional or could this be changed to `OpenIDC/pyoidc` to mirror the parental role of the github repo?

If not, could something be added to the README to explain the story on these two repos? For example of `rohe/pyoidc` is the repo for the pypi module should issues and PRs be filed against it or should they go against the parent `OpenIDC/pyoidc`?

**Comment by rohe** [comment]
[https://github.com/OpenIDC/pyoidc](https://github.com/OpenIDC/pyoidc) is the official site.
[https://github.com/rohe/pyoidc](https://github.com/rohe/pyoidc) is my own copy.

We should change the wording at PyPi.

Will do that.

**Comment by rohe** [comment]
Done

**Comment by gene1wood** [comment]
@rohe Do you think it's worth fixing in the [package settings as well](https://github.com/OpenIDC/pyoidc/blob/300adc8cdf1670f6c41dd28394958162ab5a213a/setup.py#L58)? I'm not sure if that was overlooked or if it's intentional that it's set to the URL of your copy.

**Comment by lwm** [comment]
Opened https://github.com/OpenIDC/pyoidc/issues/357 based on that @gene1wood.
