### ISSUE TITLE
accessing `/static/jwks:443` returns `gethostbyname failure`

### ISSUE THREAD

**Issue by VJalili** [OpenIDC/pyoidc#359]
I set up my oidc idp on an AWS ec2 instance. Then I'm try to define this idp in AWS IAM.
[How to create oidc idp in AWS](http://docs.aws.amazon.com/cli/latest/reference/iam/create-open-id-connect-provider.html)

This requires getting oidc idp thumbprint
[How to get oidc idp thumbprint](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html)

I'm trying to get the oidc idp thumbprint using `openssl` as follows: 

    openssl s_client -showcerts -connect ec2-instance-IP/oidc/static/jwks:443

which throws: 

    gethostbyname failure
    connect:errno=0

This is how my `jwks.json` looks: 

    {
      "keys": [
        {
          "use": "enc",
          "n": "a very long string",
          "e": "AQAB",
          "kty": "RSA",
          "kid": "op0"
        },
        {
          "use": "sig",
          "n": "a very long string",
          "e": "AQAB",
          "kty": "RSA",
          "kid": "op1"
        },
        {
          "use": "sig",
          "crv": "P-256",
          "kty": "EC",
          "y": "a short string",
          "x": "a short string",
          "kid": "op2"
        },
        {
          "use": "enc",
          "crv": "P-256",
          "kty": "EC",
          "y": "a short string",
          "x": "a short string",
          "kid": "op3"
        }
      ]
    }

Does anyone know (1) why I'm getting this error? and (2) how I can fix it?

**Comment by schlenk** [comment]
Just a wild guess.

As you try to access your AWS instance by IP address, the openssl s_client code is trying to do a gethostbyname() call to resolve the hostname for certificate checks, to verify if the hostname registered for the IP matches the one in your server certificate.

And you did not update your DNS record yet. 

Try seeing what `dig` or `nslookup` show for your setup. And maybe use one of the various `openssl s_client` debug switches to see which hostname lookup actually fails.

This isn't a question about pyoidc but about usage of `openssl` and AWS.

**Comment by lwm** [comment]
> This isn't a question about pyoidc but about usage of openssl and AWS.

In this case, closing! Feel free to re-open if there is more specific issues.

I think we'll have a mailing list for issues of this nature in the future (RE: http://idpy.org/ @rohe?)
