### ISSUE TITLE
CookieDealer.create_cookie reuses the IV for AES encryption of cookies

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#363]
The CookieDealer class has some peculiar use of the AES IV.

It creates ONE IV when the class is initialized, this is then reused for every cookie created by the class.
Depending on AES mode, this can be fatal for the security of the key. For AES-GCM it would totally ruin security, for CBC mode it is not as fatal, but still bad.

The Cookie dealer should probably use one fresh IV per cookie and store it in the cookie with the encrypted value.

**Comment by lwm** [comment]
Ah, I see! Well spotted!
