### ISSUE TITLE
Ensure that CookieDealer.srv is configured properly

### ISSUE THREAD

**Issue by decentral1se** [OpenIDC/pyoidc#365]
Follows from https://github.com/OpenIDC/pyoidc/pull/324#discussion_r120076822:

> Why not raise an exception here? Every other method in the class will blow up with an Exception if self.srv is None, so the class is in a broken state without it.

**Comment by lwm** [comment]
This should be done after https://github.com/OpenIDC/pyoidc/pull/324 is merged.

**Comment by lwm** [comment]
Also see https://github.com/OpenIDC/pyoidc/pull/324#issuecomment-306700010.
