### ISSUE TITLE
Use oic.oic.Provider.endp instead of dynamic provider.endpoints in examples

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#370]
The examples all create a list of endpoints, then call `provider.endpoints = endpoints`. For example in [op3](https://github.com/OpenIDC/pyoidc/blob/master/oidc_example/op3/server.py#L127)

But `oic.oid.provider.Provider` does not have any attribute of that name, only a method called `endpoints()` that gets overriden. The variable used in the class is called `oic.oic.Provider.endp`.

So probably the endpoints should be added to that variable instead of overwriting the method with a list.

**Comment by lwm** [comment]
> But oic.oid.provider.Provider does not have any attribute of that name, only a method called endpoints() that gets overriden.

That sounds bad!

> So probably the endpoints should be added to that variable instead of overwriting the method with a list.

I'll edit the title to reflect that, sounds like a good idea.
