### ISSUE TITLE
Point setup.py to the requirements.txt

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#376]
So far we have two inconsistent package sets listed in the setup.py and requirements.txt. I think running a `pip install -e . -r requirements/test.txt` installs different versions with the `-e .` part, and then overwrites them with the `-r ...` bit. Is there some standard way of telling the setup.py install to look in the requirements file?

**Comment by tpazderka** [comment]
I don't think so. And by looking at [python packaging](https://packaging.python.org/requirements/) guide specifications, you shouldn't be doing that anyway...
