### ISSUE TITLE
Remove arbitrary _storage_time enforcement from _iat validation

### ISSUE THREAD

**Issue by brentmclark** [OpenIDC/pyoidc#390]
According to the current `oidc` [specification](http://openid.net/specs/openid-connect-core-1_0.html) there is nothing suggesting that the `_iat` should have any impact on the validity of the token aside from ensuring that the current time (minus a small skew) falls between the `_iat` value and the `_exp` value.  

```
exp
REQUIRED. Expiration time on or after which the ID Token MUST NOT be accepted for processing. The processing of this parameter requires that the current date/time MUST be before the expiration date/time listed in the value. Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time. See RFC 3339 [RFC3339] for details regarding date/times in general and UTC in particular.

iat
REQUIRED. Time at which the JWT was issued. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.
```

However, [message.py](https://github.com/OpenIDC/pyoidc/blob/45afe8497eb9d77a468ea4823d3dbda4df8f6093/src/oic/oic/message.py#L738) is enforcing an arbitrary 4-hour token timeout based on the token's `_iat` value.

This functionality should be removed.  I will issue a PR for this removal to help further explain my message.

**Comment by schlenk** [comment]
There actually is something in the current spec that allows/suggests this kind of check:

See [3.1.3.7 IDTokenValidation](http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation), especially points 10 and 11.

> The iat Claim can be used to reject tokens that were issued too far away from the current time, limiting the amount of time that nonces need to be stored to prevent attacks. The acceptable range is Client specific.

> If a nonce value was sent in the Authentication Request, a nonce Claim MUST be present and its value checked to verify that it is the same value as the one that was sent in the Authentication Request. The Client SHOULD check the nonce value for replay attacks. The precise method for detecting replay attacks is Client specific. 

This boils down to the issue 'how to make a nonce stay single usage and validate it'. You need to store those nonces to validate that you haven't seen them yet. This is kind of a memory leak, unless you throw them away after some time. 

It is true that the iat check is useless when there is no nonce claim.
I also agree that the check in message.py seems a bit out of place, especially as the nonce storage isn't handled by message but by the `Client` class, and there is the `Client.id_token_max_age` that does the same check.

**Comment by brentmclark** [comment]
@schlenk thanks for chiming in.  I found the `nonce_storage_time` arg that `IdToken().verify()` accepts, was able to then override the 4 hour timeout.  That suits my needs well enough for now.

Fair point about the spec making room for this arbitrary enforcement.  However, I was astonished to find a 3rd-party package enforcing any value at all.  Ideally the default behavior would be to never enforcing a timeout, but then allow the user to override with a preferred value via `nonce_storage_time`.

The aforementioned change might be enough, but I do agree with your statements about the value of this `iat` check when no nonce is provided, and in contrast to the `id_token_max_age`.

All that said, I am no longer blocked by this issue after finding that `nonce_storage_time` arg.  Feel free to close this.

**Comment by lwm** [comment]
>  Feel free to close this.

Will do then! @schlenk, if you have something to follow up, re-open.
