### ISSUE TITLE
Add #315 bug #317 fix to Changelog

### ISSUE THREAD

**Issue by gene1wood** [OpenIDC/pyoidc#400]
I just encountered bug #315 in v0.10.0. and had a tough time figuring out that it was fixed in `master`. Would you update [the changelog](https://github.com/OpenIDC/pyoidc/blob/master/CHANGELOG.md) to reflect this bug and the fix in #317 in the `v0.11.0.0 [UNRELEASED]` section?

**Comment by lwm** [comment]
Thanks for calling this one in @gene1wood, I will add this to the change log.
