### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#402]
Seen in latest build of https://github.com/OpenIDC/pyoidc/pull/401 from over at https://travis-ci.org/OpenIDC/pyoidc/jobs/261507160#L345. I'll mark this as failing with a link to this issue. Hopefully someone can take a closer look soon.

**Comment by tpazderka** [comment]
It is a bug in `responses`(https://github.com/getsentry/responses/issues/161). Freeze the version at `0.6.0` and it should go away.

**Comment by lwm** [comment]
Ah, perfect @tpazderka, I'll try that soon.
