### ISSUE TITLE
Stop coveralls spamming the issues

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#404]
Whenever I'm hacking on a PR, the multiple CI runs generate coveralls reports and then the bot starts spamming the pull request with comments. It'd be nice to reduce this in some way. Creating this to track that.

**Comment by lwm** [comment]
According to https://github.com/lemurheavy/coveralls-public/issues/93#issuecomment-25119377, the owner of the coveralls account which has control over this repository can stop comments altogether. I think I'd be in favour of that - anyone against? If not, can someone do it? Otherwise, feel free to close this off - they don't seem to support only commenting once.

**Comment by tpazderka** [comment]
This is rather unfortunate since we wouldn't have any visual control over the change in coverage...

But I do understand your frustration :)
