### ISSUE TITLE
phone_number_verified is a boolean claim

### ISSUE THREAD

**Issue by zandbelt** [OpenIDC/pyoidc#407]
https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oic/message.py#L527

marks `phone_number_verified` as a string whereas the spec says it is a boolean http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

**Comment by lwm** [comment]
PRs appreciated @zandbelt! Otherwise, let's hope someone gets to this soon.

**Comment by rohe** [comment]
This is fixed by https://github.com/OpenIDC/pyoidc/pull/418.
