### ISSUE TITLE
Inconsistent release numbers/tags

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#419]
For the latest release (I haven't checked any others), there is an inconsistency in version number and tag.
Tag is `v0.11.1`, version in changelog is the same as well as version on github project page, but version in code and in PIP is `0.11.0.1`.

We should probably make them the same.

**Comment by lwm** [comment]
Ah, I see. I've done this before ;) I'll take a look soon, thanks for the report!

**Comment by lwm** [comment]
Ah, taking another look at this, it isn't my fault :) 

So, AFAICT, the code always used this `X.X.X.X` format (and I wasn't quite sure why). The tags always followed the `vX.X.X` format. All of this existed before I started co-maintaining the project. @rohe, can you clear this up this difference? Was it intentional?

> Tag is v0.11.1, version in changelog is the same

Actually, the change log conforms to the `X.X.X.X` format.

So, the fix here would be to recreate all the tags using the `X.X.X.X` format. That would be some work.

**Comment by tpazderka** [comment]
I think that the main problem is that release on Github, PIP and version in the code are not the same.

After we decide on one format, we probably can change only the last two releases?

**Comment by schlenk** [comment]
I wouldn't change the past, especially not released packages, that creates more harm than it does good. Maybe create additional tags in the repo that match what was released, for easier diffing, but even that is IMHO optional.

We should simply commit to some future format (x.x.x.x seems common for python these days) and keep that.

**Comment by rohe** [comment]
I don't think I actually had a thought through reason for using x.x.x.x . It was probably along the line @schlenk points to. Namely that it is what is commonly used.
I don't have a strong preference for x.x.x or x.x.x.x .
So, what ever the majority (hey we are a even number of collaborators so we may never resolve this :-)) decides is OK with me.
Having said that, why not continue with x.x.x.x  ?
And I agree with @tpazderka I see no reason going beyond the last two releases.

**Comment by rohe** [comment]
Along the same lines. We should have an agreement on what constitutes the difference between a moderate and a minor release.
And I don't think I've ever used the 4th digit. So in reality I've used x.x.x rather then x.x.x.x .

**Comment by tpazderka** [comment]
I am not against either of those formats. My point is to keep that consistent throughout the project :)

Minor release should be a bug fixes and such. If there are improvements, added functionality or incompatibility, I would consider it a moderate change.

**Comment by rohe** [comment]
So, since @lwm is the only one (?) that has used the 4th digit in x.x.x.x perhaps we should use x.x.x .
Can't see why we would ever need the 4th digit in our context.

**Comment by schlenk** [comment]
No preferences in either direction. x.x.x.x or x.x.x. is both fine.

**Comment by rohe** [comment]
I need to make a release ASAP, no later then the end of the day today.
If no one speaks out against it we'll use x.x.x henceforth.

**Comment by lwm** [comment]
go go go go go go go go

Also, close this 👍
