### ISSUE TITLE
sanitize function blows up on unicode characters

### ISSUE THREAD

**Issue by andrewkrug** [OpenIDC/pyoidc#421]
'ascii' codec can't encode characters in position 929-931: ordinal not in range(128)

Gets thrown by this function:

https://github.com/OpenIDC/pyoidc/blob/master/src/oic/utils/sanitize.py#L38

**Comment by lwm** [comment]
PRs gladly accepted! Especially anyone will to brave the depths of encoding handling ... a dark and dangerous place.

**Comment by andrewkrug** [comment]
This sanitize function primarily exists for stripping sensitive logs.  I see no reason why it should raise and stop login flow if it fails.

**Comment by lwm** [comment]
Yes, youre right. Its called in many places right? Perhaps it can be wrapped in a decorator and exceptions can be pased and fixed as seen (but without blocking flows). Thoughts?
