### ISSUE TITLE
userinfo_endpoint return data if access_token is expired

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#424]
Is this normal behavior?

**Comment by lwm** [comment]
That sounds like a bug to me.

Anyone else?

**Comment by schlenk** [comment]
Seems like oic.provider _do_user_info() should check for token expiry, it only checks for revocation and existance in the sdb.

**Comment by rohe** [comment]
Agree, so who makes the PR ?
Any taker.
