### ISSUE TITLE
Error in test ?

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#425]
https://github.com/OpenIDC/pyoidc/blob/cc9368d75cf56fcd58998a402e1e4cbcf07decf2/tests/test_oic_provider.py#L1135

Why using _sdb.access_token ? Maybe need _sdb.token_factory['code'] ?

**Comment by lwm** [comment]
\cc @rohe (who I notice wrote this from `git-blame`)

**Comment by rohe** [comment]
token_factory is a late comer. The test you refer to and some others using the same pattern
predates token_factory.

**Comment by lwm** [comment]
Is this OK to close off then? The functionality is the same or?

**Comment by schlenk** [comment]
It is just an alias name (see sdb.py/SessionDB) so nothing to be done really.
