### ISSUE TITLE
oic.Client usage question

### ISSUE THREAD

**Issue by swod** [OpenIDC/pyoidc#434]
My question is about the intended way of using instance of oic.Client class for relying party
service. According to note in "How to implement a Client" tutorial one instance of Client class
should be used for each OP. But what about attributes like grant and state2nonce, which are
populated in each request to OP, and there seems to be no active mechanism of clearing expired
values? The closest thing is reset method but it is never called.

So the question is what should be done to prevent this potential memory leakage from application
point or is it the library code issue?

**Comment by lwm** [comment]
Hey @swod, I'm not really sure. It's definitely worth having a discussion about.

Does anyone have any insights here? @rohe @schlenk @tpazderka

**Comment by schlenk** [comment]
Basically the lifetime of those is bound to the 'state' values still in use, but those are passed in from the outside, as part of the session state of the RP.

I doubt that the library can detect all cases when state is expired, for some special cases like expired tokens it might be possible.

So I think there should be some method to 'cleanup' a set of given state values that are no longer required. Quick and dirty one would be to `del` the states from those two dicts, but there should be an API for this.
