### ISSUE TITLE
SeeOther has no 'Location' header

### ISSUE THREAD

**Issue by artemijan** [OpenIDC/pyoidc#437]
Hello. I have class LDAPAuth(oic.utils.authn.user.UserAuthnMethod).
and implemented method "verify" where i do next (check if user exists on ldap server and then authorize him if true):

```py
authz_request = AuthorizationRequest().from_dict(query)  
return self.srv.authz_part2(username, authz_request, session_id)
```
Method authz_part2 returns a SeeOther response and I return this as a response to browser. But this response without a location header and browser just prints redirect url on the page instead of redirecting.
For now I just check if method "verify" returns "SeeOther" response then I add location header manually.
Please help me maybe I'm doing something wrong?
Thank you.

**Comment by lwm** [comment]
> just prints redirect url on the page instead of redirecting.

I'm not exactly sure but it looks like you need to return a redirect response, instead of a plain response, from your application code.

**Comment by artemijan** [comment]
So I should use flask's redirect instead of your "SeeOther" response. ok, thank you a lot

**Comment by artemijan** [comment]
I have one more question. In my app I have handler function that wraps any non-Flask response to Flask responses. (this handler converts only responses instance of oic.utils.http_utils.Response)
So, I do some transformations before and then return the response with headers from original response.
The response object here is instance of oic.utils.http_utils.Response (SeeOther in my case)
```py
return FlaskResponse(data, status, response.headers)
```
If header location is missing in original response (SeeOther) it will be missed in FlaskResponse too.
So, the question is: do I need add additional logic to check if this response is instance of "SeeOther" and add location header if it is, or it's something that should be done on your side (add location header to SeeOther response)?
Thanks.

**Comment by lwm** [comment]
I've done something similar before. I think this is another major problem with this library that it dictates the type of responses that are returned and then the application code needs to transform that response to something that their framework expects.

I think the short answer is - yes, you need to take very close care of the responses that are returned and add anything that is missing. If you'd like to raise a more general issue about response handling, we could also talk about this at length there - I think pyoidc should improve in this regard.

**Comment by lwm** [comment]
For example, here is a Flask framework resource I had to write, to add fine grain control to the responses that were being returned. Nightmare! :)

``` python
class CustomResource(Resource):
    """A flask-restful Resource subclass.

    This class provided a single new method, self.handler,
    which does the necessary conversion between the custom
    Response class that PyOIDC returns from its interface.
    We only want to return Flask style responses.
    """

    def handler(self, response):
        """Custom response handler for non-Flask responses."""
        if not isinstance(response, PyOIDCResponse):
            return response
        status = int(response.status.split(" ")[0])
        content_type = dict(response.headers)['Content-type']
        if content_type == "application/json":
            data = json.loads(response.message)
            if "error" in data:
                if "error_description" in data:
                    data = dict(errors=dict(oic=data['error_description']))
                else:
                    data = dict(errors=dict(oic=data['error']))
            return data, status, response.headers
        elif content_type == 'text/html':
            data = response.message
            return FlaskResponse(data, status, response.headers)
        else:
            location = "oidcp.views.CustomResource.handler"
            raise Exception("Missing implementation in {}".format(location))
```

**Comment by artemijan** [comment]
Seems like this code from fsfe repo (i'm working on that now) :) so in this case if SeeOther response has no location header then returned response (transformed by handler you're wrote) will not have it too?

**Comment by artemijan** [comment]
Anyway I fixed it in my app, just want to clarify :) thanks a lot

**Comment by lwm** [comment]
Haha, you're working on it! Lovely :)  Good luck with the project, happy to answer any questions, I'm sure I left it in a mess. I'll close this off now, since I think we covered what you asked. Please don't hesitate to open other issues and we'll see what we can do.
