### ISSUE TITLE
Bugs in oic.utils.authn.client.get_client_id

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#445]
1) What is this for ?
https://github.com/OpenIDC/pyoidc/blob/c0f82922d7239157db26a44d9f6768967e182baa/src/oic/utils/authn/client.py#L503
None[key]

2) https://github.com/OpenIDC/pyoidc/blob/c0f82922d7239157db26a44d9f6768967e182baa/src/oic/utils/authn/client.py#L526
Does clients dictionary contains keys like token? I can't find usage like this.

**Comment by tpazderka** [comment]
Yes, most of the library is built on the assumption of dict-like behaviour. And registration access token is also stored as a key alongside with client ID.

**Comment by ermakoves** [comment]
> Yes, most of the library is built on the assumption of dict-like behaviour. And registration access token is also stored as a key alongside with client ID.

_cinfo[_bid]  is pointless code

And if implement ClientDB, i should in some case return client_info and in some case only client id ? I think this is wrong

**Comment by tpazderka** [comment]
Ah, I can see your point now. It looks like an oversight when fixing handling of the unicode. That lie should probably should have been `_cinfo = cdb[_bid]`.

For the second question, the code seems to return clientID in all cases.
