### ISSUE TITLE
access / refresh token expiration managing

### ISSUE THREAD

**Issue by taskoma** [OpenIDC/pyoidc#448]
Good day, question about expiration times for access / refresh tokens:

What I see:

## Session DB line

```
{"authzreq": "{"prompt": ["consent"], "state": "state", "redirect_uri": "https://xyz/cb", "response_type": "code", "client_id": "WrvPHbCBpPJs", "scope": "openid offline_access email phone"}", "code": "Z0FBQUFBQmFKUHl4ZDR1ZDlTczZ6LUZ2dVNJN29WeExVdWNyaWZvMzRQdm5LZ0NZOVAyY1Nsd0hnTnpXelZkSnFqZmZpaDhQMDYtYWRHRHN5bHVqajlxZG4tVVduTWtwSFZIX2ZfbW52c0l6TUt5YU9NbXNscVl0clFrOFY0ci1pX0I2V0ZwalNYN1Fhd0IxMXM2ZTByOVhma3ZPLUp1SzlvTlJJcG5IcEJJOXlLNGU2YVgtZ2VONTBCTTV6LVZ0N2R5UGR0RzBzQUFueGtscVQ5RUFIVlY1QVNwYWtEVnRQOERhN3p1RGM2SGpCRzI5M0Q0VTBrST0=", "oauth_state": "authz", "sub": "tel:995123", "permission": "", "state": "state", "redirect_uri": "https://xyz/cb", "code_used": false, "response_type": ["code"], "authn_event": {"valid_until": 1512255104, "salt": "", "uid": "+995 123", "authn_time": 1512251504, "authn_info": "PASSWORD"}, "client_id": "WrvPHbCBpPJs", "scope": ["openid", "offline_access", "email", "phone"], "revoked": false}
```

## Refresh token information

Refresh_5yKnTXPkvCypIX3QgihazmR8KbMyjLqXIIIa77eMY7JdU4icJwDeblMAj1NQMDHO4JyS3Blp94qq2BSD

```
"{"authzreq": "{"nonce": "26503fd4-0909-4a14-afe5-d5b704896cec", "acr_values": "PASSWORD2", "prompt": ["consent"], "login_hint": "995123", "state": "d3479219-887b-4b92-8b82-7c18262cf8a0", "redirect_uri": "https://xyz/cb", "response_type": "code", "client_id": "WrvPHbCBpPJs", "upm_answer": "true", "scope": "openid offline_access email phone"}", "uid": "+995 123", "client_id": "WrvPHbCBpPJs", "sid": "c93bc2ab29bb377548503b49d3023c183e49ba0178705c7056c9477a", "scope": ["openid", "offline_access", "email", "phone"], "sub": "tel:995123"}"
```

Based on that I see
1) refresh token haven't expiration time (I can't see it). infinite ?
2) access token expiration time in authn_event.valid_until and by default it's around 1 day..

Something missed / wrong?

**Comment by tpazderka** [comment]
This mostly depends on configuration. The default value for access token is 1 hour and for 1 day refresh token.

You can see the configuration options [here](https://github.com/OpenIDC/pyoidc/blob/master/src/oic/utils/sdb.py#L343)

**Comment by taskoma** [comment]
i see, but  by fact this values haven't impact at all, or can't find place where is checked.
f.e. I setup 60 for access, 600 for refresh but in fact all works after this timelines....

+ as I mention not see this data in SessionDB instance at all

**Comment by tpazderka** [comment]
This should be dealt with in #482
