### ISSUE TITLE
Session authn_event is not AuthnEvent instance

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#481]
Usage :
https://github.com/OpenIDC/pyoidc/blob/8dca0d25ea618b10b6be1fe30b1a3a89766387c9/src/oic/oic/provider.py#L753-L755

But in session stored dict:
https://github.com/OpenIDC/pyoidc/blob/8dca0d25ea618b10b6be1fe30b1a3a89766387c9/src/oic/utils/sdb.py#L546-L555

So we will get crash.

**Comment by tpazderka** [comment]
The code in provider should either create a new instance of `AuthnEvent` from the dictionary in `sdb` or `AuthnEvent` itself should provide a way how to create such instance.

Also `AuthnEvent.to_json` is not creating JSON, so the name of the method is confusing...

**Comment by tpazderka** [comment]
* Change the `AuthnEvent.to_json()` to really return JSON.
* Change `SDB.get_authentication_event()` to return `AuthnEvent` instance
* Use `SDB.get_authentication_event()` instead of indexing
