### ISSUE TITLE
SystemRandom is not imported correctly

### ISSUE THREAD

**Issue by shelman** [OpenIDC/pyoidc#486]
In `src/oic/__init__.py`, `random.SystemRandom` is imported via the following code:
```
try:
    import random.SystemRandom as rnd
except ImportError:
    import random as rnd
```

In both python2 and python3 this yields an import error and falls back to the `random` package.

I believe the fix is to change the import to `from random import SystemRandom as rnd`. The import works locally for me but I am having some trouble with the unit tests and wanted to check in before opening a pull request.

**Comment by schlenk** [comment]
Thats bad. Yes, PR welcome. That shouldn't break any tests.
