### ISSUE TITLE
What kind of structure "cdb" should be ?

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#499]
https://github.com/OpenIDC/pyoidc/blob/3f21791df99aad8764b3ce796ba5689241ca86c4/src/oic/utils/authn/client.py#L490-L501

We got get_client_id utility where inhomogeneous structure of cdb:
`{
'client_id': client info',
'token': 'client_id'
}`

It's normal or this is a bug ?

**Comment by schlenk** [comment]
Not sure what you are really asking.

But yes, cdb is a mapping with two different items:

1) client_id => client_info
2) token => client_id

So it is normal that not all keys/values have identical structure. I would probably have used two distinct mappings instead, but well, history...
