### ISSUE TITLE
Provider auth endpoint -> _complete_authz overwrite all passed cookies

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#501]
https://github.com/OpenIDC/pyoidc/blob/3f21791df99aad8764b3ce796ba5689241ca86c4/src/oic/oauth2/provider.py#L711-L741

I think that the provider should return only those cookies that it changes or creates.
Maybe same logic exists in other endpoints

**Comment by schlenk** [comment]
Looks like a duplicate of #398 ?

**Comment by tpazderka** [comment]
Solved in #398
