### ISSUE TITLE
Crash at Introspection and UserInfo endpoints with token of deleted client

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#503]
Use case:
1) Get access token for client
2) Delete client
3) Try to verify token (introspection endpoint) or get user info

**Comment by tpazderka** [comment]
I cannot reproduce this. If I create a test for this case as you describe it, the IntrospectionEndpoint returns an error response as expected.

UserInfo endpoint is not doing any checks on client and just verifies the token so it passes as well.

Could you please provide either more info or a failing test?

**Comment by ermakoves** [comment]
Just for user_info example of failing test (tests/test_oic_provider.py ):
`

        
        def test_userinfo_endpoint_with_deleted_client(self):
        
            self.cons.client_secret = "drickyoughurt"
            self.cons.config["response_type"] = ["token"]
            self.cons.config["request_method"] = "parameter"
            state, location = self.cons.begin("openid", "token", path="http://localhost:8087")

            resp = self.provider.authorization_endpoint(request=urlparse(location).query)
            # redirect
            atr = AuthorizationResponse().deserialize(urlparse(resp.message).fragment, "urlencoded")
            uir = UserInfoRequest(access_token=atr["access_token"], schema="openid")

            global CDB
            copy_cdb = CDB.copy()
            del CDB['number5']
            resp = self.provider.userinfo_endpoint(request=uir.to_urlencoded())
            CDB = copy_cdb
            message = json.loads(resp.message)
            assert message['error'] == 'Unknown client'
`

**Comment by tpazderka** [comment]
Thanks!

**Comment by tpazderka** [comment]
I fixed the UserInfo, but I cannot reproduce it for the IntrospectionEndpoint.

I have added a [test](https://github.com/OpenIDC/pyoidc/commit/12a4d3d0520c182715fd32273ab6217ca3c327d2#diff-9452dd57bd7c4871889c100a4bcdefa8R343) so if you see what might be wrong with it, please let me know.

**Comment by ermakoves** [comment]
I have made a mistake when migrated to 13.0, sorry, my fault. IntrospectionEndpoint is alright.

**Comment by tpazderka** [comment]
OK, thanks for the update!
