### ISSUE TITLE
Remove asserts that should be conditions

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#504]
The code still has many `assert` statements that are in place of conditions.

This is bad practice and can lead to unpredictable behavior if running with an optimized code.

How to reproduce:
* Run tests with optimizations on: Add `setenv: PYTHONOPTIMIZE = 1` to tox `[testenv]` section.

Result is as follows: `50 failed, 565 passed, 1 skipped, 1 deselected`

**Comment by tpazderka** [comment]
This will be probably quite difficult since some of the failures in tests are caused by `assert` statements in `pyjwkest`...

**Comment by schlenk** [comment]
Maybe the newer cryptojwt lib by @rohe is better and we can migrate to it, to replace pyjwkest. (https://github.com/IdentityPython/cryptojwt)

The good thing would be fewer crypto libraries in the medium term, and cryptography.io seems to be the better tested/maintained one than pycryptodomex.

**Comment by tpazderka** [comment]
Other option is [pyjwt](https://github.com/jpadilla/pyjwt) which also seems to be maintained and in good state.

I do agree that we should move to cryptography...
