### ISSUE TITLE
ID Token validation

### ISSUE THREAD

**Issue by Jobbkonto** [OpenIDC/pyoidc#512]
I apologize for using this as more or less as a support forum, but I didn't know where else to go.

I'm using flask-pyoidc on top of pyoidc to connect to a provider with a static client secret, which then returns me a token. According to http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation this token is supposed to be validated, and I can't figure out if this is the case with pyoidc. Is there code for this, and is it something that happens automatically, or must it somehow be invoked?

Thanks

**Comment by schlenk** [comment]
Most of the validation is done by pyoidc automatically when decoding the response. So you get an exception when something is broken. Have a look at the code in https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oic/message.py in the `IDToken.verify()` method.

pyoidc does not do all the validations listed in the specification, but most are done as specified.
For example step 12, acr validation isn't done (as the spec doesn't say how to do it).

Closing this, as it isn't really an issue...
