### ISSUE TITLE
Faulty redirect_uri

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#528]
My client have next redirect uris: ['http://localhost:9999/auth_callback',
'http://localhost:9999/auth_callback?test=test']

When i use 'http://localhost:9999/auth_callback?test=test' in request, i getting a  Faulty redirect_uri error.

**Comment by tpazderka** [comment]
Looking at the code, I am guessing, that the registration wasn't done correctly.

The `redirect_uris` must be stored with `base` and `query` parts separated. Can you please post a content of the client registration on ClientDB?

**Comment by ermakoves** [comment]
#529
