### ISSUE TITLE
Userinfo claims added with extra_scope_dict are returned even if scope wasn't asked for

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#546]
Not totally sure if it is a bug or missing feature.

When using the 'extra_scope_dict' kwargs to create a provider, the associated claims are alway returned by the userinfo endpoint, even if only requesting scope 'openid' in the access token. Only lack of permission in the session would prevent it.

This happens here:
https://github.com/OpenIDC/pyoidc/blob/8a9dfde77fce856b32fe7cea8a1afab4bdff2d52/src/oic/oic/provider.py#L1062

The spec doesn't really mandate that the claims are restricted to the requested scope, but it is a little surprising and goes against a restrictive use of PII.

I think the code should check if one of the extra scopes is included in the session scopes and only add the claims for that case, instead of dumping all claims into the userinfo unconditionally.

**Comment by tpazderka** [comment]
I think this is a bug and the permissions should be updated to reflect this. We should not hand over claims which are not asked for.

**Comment by tpazderka** [comment]
This looks like it is actually doing it (see test added in the `extra-scopes` branch). Or am I missing something?

**Comment by schlenk** [comment]
Indeed. My code had a bug causing it.
