### ISSUE TITLE
extra_claims in token.py not used for anything other than 'kid'

### ISSUE THREAD

**Issue by valintepes** [OpenIDC/pyoidc#552]
In https://github.com/OpenIDC/pyoidc/blob/f1d7e29a3d60fa7bfc5b65a30be211a786839a8e/doc/examples/op.rst#extension-of-supported-claims-and-scopes, it is said 
`extra_claims` is used to support extra claims.  But in https://github.com/OpenIDC/pyoidc/blob/release.0.14.0/src/oic/extension/token.py, this information is only ever read in `kwargs['kid'] = self.extra_claims['kid']`.  That is, only key id is ever read from extra_claims regardless of what is actually in extra_claims.  

Am I misunderstanding this? I am relatively new to OIDC.
Also, related to my own issues in trying to use pyoidc, if I wanted to add anything to pass to an api, say some kind of user info like name or account number, how would I be able to do that if the claims are not processed?

**Comment by tpazderka** [comment]
The code you are referencing is for a JWT but the extra claims are a feature of Provider. You can pass extra claims to  your instance of Provider and the calims should be correctly processed.

**Comment by valintepes** [comment]
So I am conflating two different `extra_claims` fields?  What does `extra_claims` do in `JWTToken` then?  It is supposed to only ever contain `extra_claims['kid']`?

**Comment by tpazderka** [comment]
Yes, you are. I am not 100% sure about the `JWTToken` class but I do believe that it should only contain `kid`.

**Comment by valintepes** [comment]
What then is the proper way to add custom fields to the access JWTToken payload?  I see JWTToken.__call__ is what returns the token.  SessionDB.upgrade_to_token is what calls it.  upgrade_to_token calls JWTToken only with sid and the dictionary `sinfo`.  JWTToken.__call__ takes only fields it needs from this dic, and then it sanitizes it, then calls JWT.pack.  I don't see an opportunity to inject any kind of other data.  What am I missing?  Is it entirely elsewhere in the repo?

**Comment by tpazderka** [comment]
I don't think we have an option for this right now.

What is your usecase?
