### ISSUE TITLE
Missing project description at PyPI

### ISSUE THREAD

**Issue by zoresvit** [OpenIDC/pyoidc#555]
At the moment, it's very hard (nearly impossible) to find `pyoidc` on Python Package Index ([PyPI](https://pypi.org/)), as it doesn't show up for an intuitive search query `openid`:

![](https://i.imgur.com/nxZvR1l.png)

Also, if you search for `oidc`, you also get unrelated packages: https://pypi.org/search/?q=oidc

You can only find pyoidc by searching for `oic`, which is not a common acronym and doesn't even correspond to its GitHub repo.

Despite being just 1 of 2 Python packages certified by OpenID, the `oic` package on PyPI is missing any description, looks totally unmaintained and abandoned, certainly doesn't look like something you want to use for security purposes: https://pypi.org/project/oic/

Low version of the package (`0.14.0`) also averts the users compared to some other packages that claim to be version `1.x` and `2.x`.

PyPI is the go-to place for most Python developers and not being able to find a mature implementation of OpenID spec will lead people to using immature unverified libraries.

---

So is `pyoidc` still considered the go-to library for OpenID Connect implementation or is there anything more mature on PyPI?

If it still is, improving project description and adding relative keywords on PyPI would really help the project to be more visible. Because the only practical way to find it right now is to go to https://openid.net/developers/certified/ which, unfortunately, not many people do (most just do `pip search`).

I'm not sure if this is something that can be done via pull-request (I think PyPI description is managed by the maintainer who uploads the package), but if there are ways to help with this, please let me know.

**Comment by schlenk** [comment]
It surely is a good point.

I think @rohe maintains the PyPI description and could do something about it.

**Comment by tpazderka** [comment]
The project description can be tied to a readme. Should we do that?
