### ISSUE TITLE
Inconsistent dependencies - setup.py vs. Pipfile

### ISSUE THREAD

**Issue by ziima** [OpenIDC/pyoidc#558]
Dependencies listed in setup.py don't match those listed in Pipfile.

**Comment by tpazderka** [comment]
One of the direct dependencies (`cryptography`) is installed only because `PyOpenSSL` depends on this. This has to be fixed.

I will also regenerate Pipfile.lock with newest dependencies.

**Comment by tpazderka** [comment]
Or we can drop the Pipfile entirely and rely on setup.py for dependencies...
@rohe, @schlenk  - Your thoughts?

**Comment by schlenk** [comment]
I'm fine with dropping the pipfile. No preferences to either side. Both work for me.

**Comment by tpazderka** [comment]
Closed via #559
