### ISSUE TITLE
MissingSignKey alg=RS256

### ISSUE THREAD

**Issue by Allan-Nava** [OpenIDC/pyoidc#568]
<img width="1434" alt="schermata 2018-09-20 alle 10 21 27" src="https://user-images.githubusercontent.com/22498435/45805589-5378c800-bcbf-11e8-992b-da525efacc4d.png">

I got this error, anyone can help me ?

Thanks in advance

**Comment by schlenk** [comment]
The error tells you, that your client does not have the RSA keys to verify the signature used by the server. Provide your client with the correct keys. This usually works out of the box, if the server publishes a JWKS url and the client knows about it.

**Comment by Allan-Nava** [comment]
@schlenk ok thanks!
