### ISSUE TITLE
Drop support for python 2

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#578]
I think that it is about time we drop support for python 2. The remaining lifetime is only one year and dropping this support would allow some much needed code cleanup.

We should do a last release which would support both versions of python towards the end of the year and then drop python 2 entirely in 2019.

If we agree on this, I can focus on that.

**Comment by schlenk** [comment]
Technically, I'm sitting on a Python 2 codebase for a while still (the joy of huge legacy codebases). And will be migrating to Python 3 during the next year. So i would prefer to keep things useable for both for that time for reasons.

But i agree that it is a reasonable goal to drop Python 2 support.

**Comment by fredrikstormo** [comment]
Another option is to fork out the Python 2 support into a separate project.

**Comment by schlenk** [comment]
I also think a fork is a bad idea.

I just think end-of-year is a little to aggressive.

Imagine you are using pyoidc as an authentication system in a Python 2.7 based system. So you want to be able to update to new releases quickly, in case of security issues. It is even mandatory for some people to be able to do that. Now we drop Python 2.7 support for end of year with an effectively 4 week timeframe (christmas, new year etc.) for people to upgrade their setup to Python 3.x. 

So either we at least have plans do some kind of security only releases for the 2.7 based stuff for a while (when needed), or we should make the full switch later (e.g. 1. April 2019, 1. July, etc.).

So I would be fine with creating a branch for the old 2.7 stuff with 'security fixes only' and a branch for new development, features etc.

**Comment by tpazderka** [comment]
I meant we do a release toward the end of the year that has all the current features and still supports 2.7.
And then start working on droping the 2.7 support. That would probable mean to release 3.x version sometime in spring?

**Comment by schlenk** [comment]
Sounds like a reasonable plan, yes.

**Comment by tpazderka** [comment]
OK then, lets do a release in January, so we don't release before Christmas and then we can start working on droping Py3 support :)

**Comment by schlenk** [comment]
Guess you meant drop Py2 support ;-).
