### ISSUE TITLE
OpenID Connect Client - implementation questions

### ISSUE THREAD

**Issue by pcsegal** [OpenIDC/pyoidc#586]
Hi,

Not sure if this is the correct place to post this question, but I'm trying to integrate this library into a project that needs OpenID Connect Client functionality. Specifically, I'm following the page about how to implement a client, and I'm using the Authorization Flow (not the Implicit Flow): https://pyoidc.readthedocs.io/en/latest/examples/rp.html

My attempt is working, but I had to tweak a few things regarding how it's described in the documentation, and would like to ask it here to confirm if I'm missing something.

My test has two endpoints:
* A "login" endpoint, which instantiates the client, queries the discovery document from the provider's issuer URL, and redirects to the authorization endpoint.
* A "callback" endpoint, which processes the request to redirect_uri.

The parts that I'm not sure about are:

### 1. How should the Client should be initialized in the "callback" endpoint?

The documentation says:

> Eventually a response is sent to the URL given as the redirect_uri.
> 
> You can parse this response by doing:
>
> ```
> from oic.oic.message import AuthorizationResponse
> 
> # If you're in a WSGI environment
> response = environ["QUERY_STRING"]
> 
> aresp = client.parse_response(AuthorizationResponse, info=response,
>                               sformat="urlencoded")
> 
> code = aresp["code"]
> assert aresp["state"] == session["state"]
> ```

This snippet seems to assume that "client" is already initialized from the previous steps.

However, if I'm implementing this in a framework such as Flask, the previous steps (which trigger the authorization request) would be handled by a "login" endpoint handler, and the part that handles the redirect_uri would be in a different request handler (a "callback" endpoint). Both endpoints need to initialize the Client separately.

So, this is what I ended up doing in the redirect callback handler (this is for Flask, so I'm using a different strategy for getting the QUERY_STRING):

```
    # Create OIDC Client and initialize it with provider and client information

    client = Client(client_authn_method=CLIENT_AUTHN_METHOD)
    client.provider_config(ISSUER)  # ISSUER is the issuer URL from a global variable
    client_info = {"client_id": CLIENT_ID, "client_secret": CLIENT_SECRET} # Client ID and Client Secret are gotten from global variables
    client_reg = RegistrationResponse(**client_info)
    client.store_registration_info(client_reg)

    # Handle the authorization response

    callback_resp = client.parse_response(
        AuthorizationResponse,
        info=request.query_string.decode(),
        sformat="urlencoded")

        # [...]
```

I'm creating the client similarly in both the "login" and the "callback" handlers.

It works, but I'd like to confirm if that's how I'm supposed to do it.

### 2. Correctly doing the access token request

In the documentation, there is:

```
args = {
    "code": aresp["code"]
}

resp = client.do_access_token_request(state=aresp["state"],
                                      request_args=args,
                                      authn_method="client_secret_basic")
```

However, when trying to do that, I get an error:
```
oic.oauth2.message.MissingRequiredAttribute: Missing required attribute 'redirect_uri'
```

To make it work, I tried to adapt it by including the redirect_uri and then it worked:

```
    access_resp = client.do_access_token_request(
        state=callback_resp['state'],
        request_args={
            'code': callback_resp['code']#,
            "redirect_uri": current_app.config["HOSTNAME"]+'/callback'
        },
        authn_method="client_secret_basic",
    )
```

Should this be corrected in the documentation?

Thank you.

**Comment by tpazderka** [comment]
There is a [mailing list](https://lists.sunet.se/listinfo/pyoidc-dev) for questions about implementation.

As for your questions:
0) The examples are somewhat outdated and may not be 100% accurate on all accounts. This is something we hope to change soon. Any pull requests are welcome :)
1) There are many possible ways how to restore a consumer state. [cookie](https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oic/consumer.py#L28), [restore](https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oic/consumer.py#L161) and probably many others.
Your use of static configuration seems perfectly OK if that is something that works for your usecase.
2) You can use [Consumer.complete](https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oic/consumer.py#L378) as a higher level function which should do most of the work. And yes, the documentation is probably not accurate there.
