### ISSUE TITLE
alabaster should not be in runtime deps

### ISSUE THREAD

**Issue by artofhuman** [OpenIDC/pyoidc#598]
Hi, ✋ 

As I can see the `alabaster` dependency used only for documentation in https://github.com/OpenIDC/pyoidc/blob/master/doc/conf.py#L1.
I think this dependency needed only for developers, not in install deps https://github.com/OpenIDC/pyoidc/blob/master/setup.py#L88

**Comment by tpazderka** [comment]
Thanks for the report. The dependency should be moved to `docs` extras.

**Comment by tpazderka** [comment]
Merged.
