### ISSUE TITLE
Move Message classes to class variables

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#631]
Many methods on `Server` and `Client` take `Message` class as a `kwarg`. This creates a need to override the method if we need to change the class (especially for `Provider)`.

It might be beneficial to make them a class variable and allow to override them in `__init__` perhaps by parsing a dictionary in order to not clutter the kwargs on the init method.

**Comment by tpazderka** [comment]
@schlenk Any objections or thoughts?

**Comment by schlenk** [comment]
Sounds halfway reasonable. 

I see mostly pairs of request/response classes there, sometimes the response classes are hidden from sight one layer deeper. Most end up in parse_response() or construct_request() one way or the other, so this smells a bit like a pair of factories that could be extracted into their own classes.

A bit like have a factory class, register the message pairs (request/response) under some symbolic name and use those in client/server where needed. Then pass in the factory into the constructor somewhere.

**Comment by tpazderka** [comment]
The coupling of request/response cls makes sense. My idea was to have a dictionary with mapping of message type to class and pass that as a single kwarg to provider/server/client. 

It might not necessarily be a dictionary, but an object with attributes. The value in the mapping can be a tuple with request/response as elements.
