### ISSUE TITLE
Provider looses symmetric key of dynamic clients on restart

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#639]
When a client registers dynamically and requests encryption, this adds a key dervived from the client secret to the keyjar. This key will be used to encrypt userinfo and id_token responses, if the client asked for symmetric encryption. For RSA the jwks_uri provides the keys, so that works.

This is defined in:
https://openid.net/specs/openid-connect-core-1_0.html#Encryption (Symmetric Encryption)

But as the keyjar has no persistence option, that symmetric key is lost during a restart, so a client trying to authenticate after an OP restarts, causes an failure to encrypt.

The key should be re-added to the keyjar as needed, as it is done during client registration:
https://github.com/OpenIDC/pyoidc/blob/f4781ba38fad0f299ca7d17fcff42a5ca3fdd00d/src/oic/oic/provider.py#L1555

Or the keyjar needs a persistence option...

**Comment by schlenk** [comment]
Just saw:
https://github.com/OpenIDC/pyoidc/blob/f4781ba38fad0f299ca7d17fcff42a5ca3fdd00d/src/oic/utils/keyio.py#L1176

so we already have code to refresh the keys, but it is only used for decrypt & verify, not for the encrypt path.

**Comment by tpazderka** [comment]
In case of encrypt, there is an attempt to add the key:
https://github.com/OpenIDC/pyoidc/blob/f4781ba38fad0f299ca7d17fcff42a5ca3fdd00d/src/oic/oic/provider.py#L368-L370

Or do you mean something different?

**Comment by schlenk** [comment]
Ah, i got a report for the userinfo endpoint, so maybe it works for id_token. Will check.

**Comment by tpazderka** [comment]
Ah, I see:
https://github.com/OpenIDC/pyoidc/blob/f4781ba38fad0f299ca7d17fcff42a5ca3fdd00d/src/oic/oic/provider.py#L870-L882

This is used in userinfo and only handles `jwks` and `jwks_uri`, so that might be a source of your issues.

**Comment by schlenk** [comment]
Yes, thats the code i had in mind. 
Seems it is an unusal setup, to request encrypted userinfo but not encrypted id_tokens.

**Comment by tpazderka** [comment]
OK, I will probably make it a helper function and replace the different approaches with that. There seems to be couple places where this is repeated.

**Comment by tpazderka** [comment]
OK, I think we need to revisit this.

Just ran into an issue with `jwt_bearer` assertion failing when `jwks_uri` is not registered and the keys were registered directly.

Since both functions have slightly different purpose, we will need to update `check_key_availability` as well. It needs to take into account keys registered using `jwks` as well.
