### ISSUE TITLE
Client secret is derived from random.random() instead of the cryptographically secure SecureRandom

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#640]
See #206 .

This time it is the client secret which gets less entropy then it should get.
https://github.com/OpenIDC/pyoidc/blob/f4781ba38fad0f299ca7d17fcff42a5ca3fdd00d/src/oic/oic/provider.py#L116

The whole construction for `secret()` is a bit weird anyway, it should probably just grab enough entropy from os.urandom(), maybe mix in some more, but no need to use a HMAC here...

**Comment by tpazderka** [comment]
We can probably reuse the `oic.rndstr` that already has a logic to pick the most secure implementation or random number generator, no need to duplicate the logic.

**Comment by tpazderka** [comment]
Btw, the weird construction is there probably to ensure consistent length?

**Comment by schlenk** [comment]
Yes. But it is still weird. A simple hash would have been enough, a HMAC is only useful if you want to check integrity, which makes no sense at all for a secret key.

The usual way to do that would be just use `os.urandom()` and maybe mix in some extra entropy from other sources and maybe a KDF on top, if in doubt about the entropy source. Thats basically what the secrets module does.

If we were on Python 3.6, i would just use 'secrets.token_hex()' and make the size big enough to have 512 bits of entropy (enough for a 256-bit AES 256 key + a 256-bit HMAC key). For use as a client secret less would be fine (around 128 bit or so), but as the secret is reused for key derivation more entropy is better.

https://docs.python.org/3/library/secrets.html

**Comment by tpazderka** [comment]
Hm, the `token_hex` looks ideal, so once we drop Python 3.5 ... :)

The current size is 56 if I am not mistaken.

**Comment by schlenk** [comment]
Yes, but the important part is how many bits of entropy goes into the construction. The end size is determined by the SHA224 construction, it is just 224-bits/4-bit per hex char = 56 chars.

But the actual entropy we got for the key was:

- time.time(), e.g. how good can someone guess the time the secret was generated, usually to less than a month, so far less than 32-bits.
- sid = client_id, publicly visible, so entropy bits for the key is 0
- random.random(), mersenne twister AFAIK (https://crypto.stackexchange.com/questions/66622/what-is-the-entropy-of-a-mersenne-twister-mt) , so if someone can register lots of clients, the entropy is basically zero after 624 client registrations

Now we got a seed from the provider, but that defaults to the empty string b"", so the HMAC adds no security either.

Leaves us with just the time as valid entropy for the client secret. That is worse than SSLv1:
https://en.wikipedia.org/wiki/Random_number_generator_attack#Predictable_Netscape_seed

**Comment by tpazderka** [comment]
Yes, sorry I read that as size and not entropy for some reason...

Now we have the entropy a little better. The depletion of entropy using repeated client registrations should probably be mitigated by rate limiting on the registration endpoint, which I would consider as a must.
