### ISSUE TITLE
Deprecate refresh_db

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#644]
I think it is about time to end the duality around Refresh tokens. Both access code and access token use TokenFactory, so we should go that route as well.

The only issue I can see right now, without to much digging into is the lack of session info storage. For example, this test would fail for `DefaultToken`:

https://github.com/OpenIDC/pyoidc/blob/e94b8129c26d7c9acd1ae3c4dbfe914efedc7381/tests/test_sdb.py#L272-L287

We can either implement a storage to the `DefaultToken` or we will just assume that the `SessionDB` internal database never gets cleared?

**Comment by tpazderka** [comment]
@schlenk Any thoughts?

**Comment by schlenk** [comment]
Agreed that all tokens should come from just one Token Factory, no reason to have different ones.

But I think we need to think about token persistence in general. Like https://github.com/OpenIDC/pyoidc/issues/146 mentions, the `SessionDB` lacks in that area.

I am not sure if one wants to merge the refresh and access token storage too closely, as those have different security and lifetime properties. There might be reasons to protect the more powerful refresh tokens with stronger (slower) encryption/HSMs, while access tokens should be fast, which would collide with a naive unified storage design.

**Comment by tpazderka** [comment]
I do agree with your reasoning against unified storage. We can probably add a kwarg to the `DefaultToken` that would be the underlying storage and make it required when the `typ=R`. That would allow users to implement a suitable storage method for refresh tokens and wouldn't bother users who do not issue refresh tokens.

I will have a look at #146, it looks that it only needs a small changes.
