### ISSUE TITLE
Use auto-formatter

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#645]
I was considering to use an auto-formatter for code style enforcing (and validation).

The current state of the code is a mix of code styles and I believe it is not very readable. Making the code formatting more consistent should help that.

I was mainly looking at [black](https://github.com/ambv/black) which is not configurable and strives for minimal diff on code changes. It has a check mode to integrate in to CI.

Other options are [yapf](https://github.com/google/yapf) which is more configurable and has some settings to tailor the output. It doesn't have a check mode so we would need to get creative.

Any opinions?

**Comment by schlenk** [comment]
Sounds useful. I don't have a real opinion if black or yapf is better.  
Both need a Python 3.6, so they clash a little with our 3.5 support, but thats a minor issue as it is just a development tool.

As we don't have multiple branches that need merges now, it would be a good time to do it now and reformat things.

Might be helpful to have a snippet for an appropriate pre-commit hook.

**Comment by tpazderka** [comment]
They need a Py3.6 for running but can format code with Py3.5 support, so we should be fine.

I am not sure about pre-commit hook, I was more thinking about a target in Makefile and add a check to `quality` build.

I do agree that now is a good time :)

**Comment by tpazderka** [comment]
As a benefit, we can probably drop some of the other linters ...

**Comment by tpazderka** [comment]
Preview for black in #647

**Comment by tpazderka** [comment]
Closed by #647.
