### ISSUE TITLE
Client assertions

### ISSUE THREAD

**Issue by denali-lph** [OpenIDC/pyoidc#654]
The use of client assertions for authentication at the token endpoint in the OIDC authorization code flow is not described in the RP documentation or demonstrated in the RP examples.  This would be beneficial, and my purpose for this issue is to provide some fodder.  I specifically address using client assertions to authenticate with a Microsoft Azure AD IdP, which involves creating a custom assertion.

First, the out-of-band RP registration guidance in pyoidc's documentation only discusses registering a client using a client secret, without noting any alternative.  When using client assertions, the _client_secret_ item would obviously not be included. 

Support for client assertions is provided in the _do_access_token_request_ method of the oic.oic.Client class, using keyword arguments to the method:
```
            kwargs = dict(algorithm="RS256", authn_endpoint='token',
                          authn_method="private_key_jwt")
```
The _authn_method_ parameter initiates authentication with a client assertion.  The _algorithm_ and _authn_endpoint_ parameters are needed by the oic.utils.authn.client.PrivateKeyJWT class to properly construct the assertion.  Also required is a signing key in the client's keyjar.  A way to accomplish this is illustrated by the TestPrivateKeyJWT class in tests/test_client.py.

The payload of the resulting JWT can be understood from the _assertion_jwt_ function in oic.utils.authn.client.  Determining which header claims are generated involves more digging, and only the _alg_ claim is included.

As I stated upfront, my goal for using client assertions was authenticating at the token endpoint of a Microsoft Azure AD tenant IdP.  Microsoft provides this [guidance](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials).  The differences from the client assertion pyoicd normally generates are:

- the _typ_ and _x5t_ header claims must be included.
- the payload claim _iat_ is instead _nbf_

pyoicd nicely provides a _client_assertion_ keyword parameter when calling _client.do_access_token_request_.  The value replaces the client assertion pyoidc would normally generate.  Note that the other keyword arguments identified above are still required:
```
            kwargs = dict(algorithm="RS256", authn_endpoint='token',
                          authn_method="private_key_jwt",
                          client_assertion=custom_assertion)
```
Generating a custom client assertion for Microsoft is illustrated by the function below.
```
import json
from jwkest.jws import JWSig, SIGNER_ALGS
from jwkest.jwt import b64encode_item
from oic import rndstr
from oic.utils.time_util import utc_time_sans_frac


def make_assertion(client_id, token_endpoint, fingerprint, key, lifetime=60):
    """Creates a JWT for IdP token endpoint auth per Microsoft specs"""
    _alg = "RS256"
    headers = {'alg': _alg, 'typ': "JWT", 'x5t': fingerprint}
    _now = utc_time_sans_frac()
    payload = dict(
        iss=client_id,
        sub=client_id,
        aud=token_endpoint,
        jti=rndstr(32),
        nbf=_now,
        exp=_now + lifetime
    )
    jwt = JWSig(**headers)
    _signer = SIGNER_ALGS[_alg]
    _input = jwt.pack(parts=[json.dumps(payload)])
    sig = _signer.sign(_input.encode("utf-8"),
                       key.get_key(alg=_alg, private=True))
    return ".".join([_input, b64encode_item(sig).decode("utf-8")])
```
The _client_id_ and _token_endpoint_ arguments to this function should be straightforward.  _key_ is a _jwkest.jwk.RSAKey_.   To create one from a certificate private key file at _path_:
```
from jwkest.jwk import rsa_load, RSAKey
signing_key = RSAKey(key=rsa_load(path), kty="RSA", use='sig')
```
_fingerprint_ is a Base64 encoded SHA-1 fingerprint of the X.509 certificate corresponding to the private key.  Microsoft Azure AD displays this fingerprint as a hexadecimal string when the certificate is registered during IdP configuration.  You can easily convert this string (as _hex_string_) by:
```
from base64 import b64encode
from binascii import unhexlify
fingerprint = b64encode(unhexlify(hex_string))
```
If you don't have the hexadecimal fingerprint, but you have the X.509 certificate file, you can generate the fingerprint, as shown below using the _cryptography_ package:
```
from base64 import b64encode
from binascii import hexlify
from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
with open("cert.pem", "rb") as f:
    cert = x509.load_pem_x509_certificate(f.read(), default_backend())
fingerprint = cert.fingerprint(hashes.SHA1())
hexadecimal_fingerprint = hexlify(fingerprint).upper()
base64_fingerprint = b64encode(fingerprint)
```
Putting it together
```
def make_token_request(client, state, code, redirect_uri, scopes, assertion):
    """Retrieves tokens by redeeming an authorization code"""
    request_args = dict(
        client_id=client.client_id,
        code=code,
        redirect_uri=redirect_uri
    )
    kwargs = dict(
        algorithm="RS256",
        authn_endpoint='token',
        authn_method="private_key_jwt",
        client_assertion=assertion,
        request_args=request_args,
        scope=scopes,
        state=state
    )
    return client.do_access_token_request(**kwargs)
```

**Comment by schlenk** [comment]
Thanks for the nice description.

**Comment by tpazderka** [comment]
Thank you, are you willing to submit a PR?

**Comment by denali-lph** [comment]
Could be.  Where would you want it to go?  Features Cookbook?

**Comment by tpazderka** [comment]
Yes, that seems like a good place. Thanks!

**Comment by tpazderka** [comment]
Merged.
