### ISSUE TITLE
access_token verification method / where to get signature verifier object / public key

### ISSUE THREAD

**Issue by gumond** [OpenIDC/pyoidc#665]
Hello, I have a basic OP client implemented using pyoidc library according to the docs. This client is supposed to be an 'admin client', i.e. users contacting our system can provide their access_tokens and we would wish to use these in order to perform actions on behalf of the user. Our 'admin' OP client and the user OP clients are independent and are both based on the same OP.

Is it possible to verify any received access_token, knowing the issuer and having my own client configured on the same OP ? How could I do this using the pyoidc library without contacting the OP repetitively for several tokens ?

Is it possible to perform actions with such access_token on behalf of the user ?

Many Thanks for any insight !
Cheers,
Jaroslav

_Originally posted by @decentral1se in https://github.com/OpenIDC/pyoidc/issues/182#issuecomment-281437336_

**Comment by schlenk** [comment]
The short answer is  No, not in general.

The access_token format is totally controlled by the OP, so a client cannot validate it alone. Thats the reason you need RFC 7662 or some other network call to verify it. 

So in general you cannot do this. But you can do it sometimes, if the OP chose to use JWT as the format for its access_tokens and provides the necessary keys to validate it. But thats out of scope for the client and just generic JWT tests.

**Comment by gumond** [comment]
All clear, Many thanks !
