### ISSUE TITLE
What is the first release that can work with python 3.6+?

### ISSUE THREAD

**Issue by haoyuanli** [OpenIDC/pyoidc#668]
Migrating from 0.7.6, which doesn't work with Python 3.6+

Any idea what is the first release of oic that does support 3.6+? I looked through the release notes, didn't seem to get mentioned anywhere. Upgrading to the latest oic==0.15.1 is certainly the ultimate goal, but upgrading to the first release that supports 3.6+ first just helps me debug the legacy codebase

thanks a lot

**Comment by tpazderka** [comment]
Judging by the history of setup, it looks like 0.11.0 might be the version you are looking for.

**Comment by haoyuanli** [comment]
Thanks a lot!

**Comment by tpazderka** [comment]
You are welcome!
