### ISSUE TITLE
Investigate request_info for password argument

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#683]
ok. It is wrong in any case, so the fix should do no harm, but probably the issue is burried somewhere in request_info().

_Originally posted by @schlenk in https://github.com/OpenIDC/pyoidc/pull/682_

**Comment by schlenk** [comment]
From a cursory look, i would guess it gets passed in via oic.utils.authn.client.ClientSecretBasic.construct() when someone passes 'password' in the http_args. Maybe ClientSecretBasic should remove password from http_args in that case?

**Comment by tpazderka** [comment]
Yes, `password` is definitely used there, so maybe yes. Will have a look later today.

**Comment by tpazderka** [comment]
So a little bit more digging later... This turns out to be a case where the password should have been used as an authentication method, but is never passed to `ClientSecretBasic` and remains in `http_args`.

So a fix in client is in order.
