### ISSUE TITLE
Authorization Code Flow not return refresh_token

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#686]
Hello. Why when i use Authorization Code Flow, provider not return refresh token? To get refresh token i need to refresh access token as soon as i got him. Specification example - https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse

**Comment by ermakoves** [comment]
Maybe problem in that refresh_token is optional ? And by default argument issue_refresh not sending.
https://github.com/OpenIDC/pyoidc/blob/699871be6345eaf07ca4cf829b7f29f64aded842/src/oic/oic/provider.py#L999-L1001
https://github.com/OpenIDC/pyoidc/blob/699871be6345eaf07ca4cf829b7f29f64aded842/src/oic/utils/sdb.py#L635-L644

**Comment by tpazderka** [comment]
Yes, but just a few lines above, you set `issue_refresh` to `True` if it is permitted.

https://github.com/OpenIDC/pyoidc/blob/699871be6345eaf07ca4cf829b7f29f64aded842/src/oic/oic/provider.py#L990-L1001

**Comment by ermakoves** [comment]
So it is must be like application configuration ?

**Comment by tpazderka** [comment]
Possibly. Can you have a look what is stored in the `permissions`?

**Comment by ermakoves** [comment]
permissions is empty string by:
https://github.com/OpenIDC/pyoidc/blob/699871be6345eaf07ca4cf829b7f29f64aded842/src/oic/utils/authz.py#L11-L18

So we have two ways:
1) set issue_refresh by application
2) set scope offline_access

**Comment by tpazderka** [comment]
You certainly need to set the scope to contain `offline_access`.

**Comment by tpazderka** [comment]
Closing as this is probably usage issue. If you think that this really is an issue, then please reopen.
