### ISSUE TITLE
Release missing

### ISSUE THREAD

**Issue by big-kahuna-burger** [OpenIDC/pyoidc#691]
Did someone forgot to `make release` of `1.0.1`, or is it intentional?

**Comment by schlenk** [comment]
The release is here
https://github.com/OpenIDC/pyoidc/releases

And a pypi version is also available:
https://pypi.org/project/oic/#files

So please clarify what you find missing exactly?

**Comment by big-kahuna-burger** [comment]
My bad. Need the py3, seems like 0.35 is the last one that gets installed with python 2.7
