### ISSUE TITLE
If birthdate is `None`, validation fails

### ISSUE THREAD

**Issue by timothy-spencer** [OpenIDC/pyoidc#692]
In `src/oic/oic/message.py`, the OpenIDSchema verify function seems to try to verify that the birthdate is a proper date format, but this fails if it is `None`.  I'm not sure why I'm running into this, but not others, but it is preventing me from claiming my auth token from a login.gov IDP.

I'm generating a PR right now for this which seems to fix it, but I am not 100% sure that I understand what is going on here, like why this isn't something that everybody runs into, so I will definitely be looking for feedback from folks who know the code better!

Thanks!

**Comment by schlenk** [comment]
The spec clearly defines the birthdate claim as a string:

> 

birthdate | string | End-User's birthday, represented as an 	  ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD 	  format. The year MAY be 0000, indicating that it is omitted. 	  To represent only the year, YYYY format is allowed. Note that 	  depending on the underlying platform's date related function, providing just year can 	  result in varying month and day, so the implementers need to take this factor into account 	  to correctly process the dates.
-- | -- | --

(see https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims )

So ``None`` is not a valid value for this claim and the validation should fail.

**Comment by tpazderka** [comment]
AFAIK if there is no value, the claim should not be included.

**Comment by timothy-spencer** [comment]
Hmm.  Interesting.  I thought it was just checking the format of the claim.  That seems reasonable, though it is unsatisfying to me, because I'd really love to just get this working.  :-)  I guess I'll try to dig into this some more to see why birthdate is in there and is None.  Thanks!

**Comment by selfissued** [comment]
@tpazderka is correct.  As Connect Core says at https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse, "If a Claim is not returned, that Claim Name SHOULD be omitted from the JSON object representing the Claims; it SHOULD NOT be present with a null or empty string value."

**Comment by Allan-Nava** [comment]
> AFAIK if there is no value, the claim should not be included.

if the value is None how can I fix this problem?

**Comment by tpazderka** [comment]
The claim should not be included. That needs to be fixed on the other side.

**Comment by Allan-Nava** [comment]
> The claim should not be included. That needs to be fixed on the other side.

So inside the keycloak admin console?

**Comment by tpazderka** [comment]
Not sure what can and cannot be done in the console, but I would suspect that it is an error in their implementation.

**Comment by Allan-Nava** [comment]
Ah okay because I use facebook social login but it can't retrieve the birthdate so this is an example:

<img width="1378" alt="Screenshot 2019-11-29 at 14 36 21" src="https://user-images.githubusercontent.com/22498435/69872465-beeff980-12b5-11ea-9034-ecd6d377afc3.png">

so it pass the variable birthdate but None

**Comment by tpazderka** [comment]
Yes, it looks like their implementation. They empty values should not be included and are breaking interoperability. I would suggest to raise an issue with them.
