### ISSUE TITLE
Client Registration with Inital Access Token does not work with Keycloak

### ISSUE THREAD

**Issue by JustKiddingCode** [OpenIDC/pyoidc#718]
Hi,

The functionality to registers one's client via an initial access token
does not work with the keycloak server, maybe other Providers as well. The functionality (introduced with 7377a7a4e5e185363e)
takes an arbitrary string, base64 encodes it and adds it to a header.
Creating a registration token with keycloak already gives us an base64 encoded token. So the token gets double b64 encoded
and therefore rejected.
b64-Decoding it beforehand does not work because then we have a bytes object with a RSA Signature which cannot really be be decoded to a string object.
So, I see two possibilities:
* Add a other parameter for already b64 encoded strings
* Check if the token is b64 encoded, use it if it is, else b64- encode it.

I could implement both (or other solutions), just tell me what's more appropriate.

**Comment by tpazderka** [comment]
I prefer the later. If you want to submit a PR, that would be awesome!
