### ISSUE TITLE
Birthdate keycloak 8.0 return birthdate='None'

### ISSUE THREAD

**Issue by Allan-Nava** [OpenIDC/pyoidc#722]
How can I fix this problem with keycloak 8.0?

**Comment by tpazderka** [comment]
That is unfortunately a bug on Keycloak side. See #692 for explanation.

I would suggest you raise an issue with them.

**Comment by Allan-Nava** [comment]
Okay thanks for having responded immediately

**Comment by tpazderka** [comment]
No problem, please link the keycloak issue to here, so we can keep track.

**Comment by Allan-Nava** [comment]
I can't to create the new issue inside keycloak: https://github.com/keycloak/keycloak/

**Comment by tpazderka** [comment]
They use [JIRA](https://issues.jboss.org/projects/KEYCLOAK/issues/KEYCLOAK-12277?filter=allopenissues).

**Comment by Allan-Nava** [comment]
We can't do nothing to retrieve the birthdate, right?

**Comment by tpazderka** [comment]
If you asked for the birthdate and they do not provide it, than it is a question for them.

**Comment by tpazderka** [comment]
Closing this as it is not our bug.
