### ISSUE TITLE
How to request a token for the client using client_credentials grant. 

### ISSUE THREAD

**Issue by gumond** [OpenIDC/pyoidc#724]
I can not figure out how I can request a token for my client using client_credentials grant. Could you help me ? 
[1] https://auth0.com/docs/flows/guides/client-credentials/call-api-client-credentials

**Comment by gumond** [comment]
The only way I found is to create a dummy Grant with a dummy grant code e.g. code = "client_credentials_code" and simulate the authorization code flow, i.e.: 

args = {"client_id": OIDC_client.client_id,
        "client_secret": OIDC_client.client_secret,
        "grant_type": "client_credentials",
        "scope": "profile",
        "audience": "world",
        "code": "client_credentials_code",
        "redirect_uri": "dummy"
        }
OIDC_client.do_access_token_request(state=client_creds_session_state, request_args=args, authn_method="client_secret_basic")

But this does not seem like the right way to go.

**Comment by tpazderka** [comment]
You are actually not creating a Grant. You are just passing some arguments to the `do_access_token_request`. It should be possible to skip the `code` and redirect_uri` (as that should be ignored anyway).

**Comment by gumond** [comment]
So how it comes that I get this error ? 

```
>>> OIDC_client = OIDC_CLIENTS['https://iam.extreme-datacloud.eu/']
>>> args = {"client_id": OIDC_client.client_id,
...         "client_secret": OIDC_client.client_secret,
...         "grant_type": "client_credentials",
...         "scope": "openid profile",
...         "audience": "rucio"}
>>> oidc_token = OIDC_client.do_access_token_request(request_args=args, authn_method="client_secret_basic")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/oic/oic/__init__.py", line 674, in do_access_token_request
    authn_method, **kwargs)
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 720, in do_access_token_request
    **kwargs)
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 442, in request_info
    **kwargs)
  File "/usr/lib/python2.7/site-packages/oic/oic/__init__.py", line 541, in construct_AccessTokenRequest
    extra_args, **kwargs)
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 362, in construct_AccessTokenRequest
    grant = self.get_grant(**kwargs)
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 281, in get_grant
    raise GrantError("No grant found for state:'%s'" % state)
oic.oauth2.exception.GrantError: No grant found for state:''
```

**Comment by tpazderka** [comment]
Hm, first of all, it looks like you are using OIDC client where you should be using OAuth client.

You should also set the request_type to `CCAccessTokenRequest`.

Aside of this, we probably presume that you should have authorized beforehand and thus should have the grant already in storage. These types of flow have been neglected in the past, so it is possible they do not work 100%.

Most of the OAuth code has been implemented as a sort of side-effect of implementing OIDC.

**Comment by gumond** [comment]
Thank you very much for your response ! You are right, I am initialising my client (with my client_secrets dict) using: 

 ```
client = oic.oic.Client(client_authn_method=CLIENT_AUTHN_METHOD)
            client.provider_config(issuer)
            client_reg = RegistrationResponse(**client_secret)
            client.store_registration_info(client_reg)
```

So it is OIDC client as you say. I see this class inherits from the OAuth2.0 client, which you suggest to use, right ? 

I see CCAccessTokenRequest commented out on line 71 of [1]. Also when looking at the definition of construct_AccessTokenRequest the only request_type excluded from checking grant is the construct_AccessTokenRequest, the others will require a grant. How do I get one ? 

[1] https://github.com/OpenIDC/pyoidc/blob/9623bf47b4a72e7f626883eb5415788c73cee85a/src/oic/oauth2/__init__.py

**Comment by gumond** [comment]
AFAIU [1], it should be access token request, but I might be mistaken. As I see it, on the client side I should not expect any grant - my client_id and client_secret should be the "grant". 

[1] https://tools.ietf.org/html/rfc6749#section-4.4
> 4.4.1.  Authorization Request and Response
> 
>    Since the client authentication is used as the authorization grant,
>    no additional authorization request is needed.

**Comment by gumond** [comment]
With OAuth2.0 client I still do not succeed because of the grant missing - see below. And when trying to use CCAccessTokenRequest, it does not convert it to the endpoint because line (71)  of the init file is commented out: 

```
>>> client.do_any(CCAccessTokenRequest, request_args=args, authn_method="client_secret_basic")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 777, in do_any
    endpoint=endpoint)
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 468, in request_info
    **kwargs)
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 422, in uri_and_body
    uri = self._endpoint(self.request2endpoint[reqmsg.__name__],
KeyError: 'CCAccessTokenRequest'
>>> from oic.oauth2.message import AccessTokenRequest
>>> client.do_any(AccessTokenRequest, request_args=args, authn_method="client_secret_basic")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 777, in do_any
    endpoint=endpoint)
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 442, in request_info
    **kwargs)
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 362, in construct_AccessTokenRequest
    grant = self.get_grant(**kwargs)
  File "/usr/lib/python2.7/site-packages/oic/oauth2/__init__.py", line 281, in get_grant
    raise GrantError("No grant found for state:'%s'" % state)
oic.oauth2.exception.GrantError: No grant found for state:''
```

**Comment by tpazderka** [comment]
Ah, true. I haven't delved into this part of Oauth specs since this is disallowed in OIDC.

My guess is that you are hitting a flow that hasn't been properly implemented. 

Feel free to make a new issue about it here (or update the title/description of this one). If not, I will make it later today. As for now, you can probably use the workaround you have found.

**Comment by gumond** [comment]
Thank you for the prompt responses ! 

I have now, Thanks for you, found a second work_around, probably less abusing the code than the previous one: 

```
>>> from oic.oauth2.message import CCAccessTokenRequest
>>> from oic.oauth2 import REQUEST2ENDPOINT
>>> REQUEST2ENDPOINT['CCAccessTokenRequest']='token_endpoint'
>>> client.do_any(CCAccessTokenRequest, request_args=args, authn_method="client_secret_basic")
```


Unrelated to this question, I have a second situation when I have to create an 'artificial grant' using the OIDC client which tries to ask for token exchange, is this expected  or should this be rather asked by the OAuth2 client as well ?

**Comment by tpazderka** [comment]
This workaround looks a little better :)

My guess is that this is also a partial/faulty implementation of OAuth parts. Please file an issue with description and code snippet/test case.

**Comment by tpazderka** [comment]
Closing as this is a usage question that resulted in bug/enhancement request. No need to keep this open.
