### ISSUE TITLE
Missing a capability of OAuth 2.0 client asking for token exchange using extension grant

### ISSUE THREAD

**Issue by gumond** [OpenIDC/pyoidc#728]
According to [1] and [2] an OAuth 2.0 client should be able to exchange user's token for another one with modified e.g. scopes and audiences (as defined/allowed on the side of the Identity Provider).  This does not seem to be currently implemented at all. A workaround illustrated in [3] (using an OIDC client) seems to work for the moment, but does not reflect the use case properly. 
I admit that it is not entirely clear to me, whether the token exchange should be a matter of OIDC client of OAuth 2.0 client, but I did not find another way to do this than by creating an unnecessary grant in [3]. 

[1] https://tools.ietf.org/id/draft-ietf-oauth-token-exchange-14.html#rfc.section.2
[2] https://tools.ietf.org/html/rfc6749#section-4.5
[3] 
```
        OIDC_client = OIDC_CLIENTS[issuer]
        # create a grant instance of the OIDC_client
        exchange_session_state = rndstr(50)
        OIDC_client.grant[exchange_session_state] = Grant()
        OIDC_client.grant[exchange_session_state].grant_expiration_time = time_util.utc_time_sans_frac() + 60
        OIDC_client.grant[exchange_session_state].code = "exchange_code"
        resp = AccessTokenResponse()
        resp["subject_token"] = subject_token
        OIDC_client.grant[exchange_session_state].tokens.append(Token(resp))

        # assembling parameters to request a new access token
        args = {"subject_token": subject_token,
                "scope": jwt_row_dict['authz_scope'],
                "audience": jwt_row_dict['audience'],
                "grant_type": grant_type}
        # exchange access code for a access token
        oidc_token_response = OIDC_client.do_any(Message,
                                                 endpoint=OIDC_client.provider_info["token_endpoint"],
                                                 state=exchange_session_state,
                                                 request_args=args,
                                                 authn_method="client_secret_basic")

```

**Comment by tpazderka** [comment]
It appears that the Extension Grant is not implemented at all.
