### ISSUE TITLE
Requesting access token refresh using refresh token via a OAuth2/OIDC client. 

### ISSUE THREAD

**Issue by gumond** [OpenIDC/pyoidc#730]
According to [1] an OIDC client which previously issued an access and refresh token to the user should be allowed to refresh such access token asking the identity provider. I did not find a straightforward way to make this happen except [2]. A Grant is currently expected for most OIDC client methods, but this use-case does not seem to need any grant. Do you think OAuth2 client would be a better candidate to implement this feature ? If so, the first access token would need to be issued by OAuth2 client and not by OIDC client as the refresh tokens are bound to the client ? Is this currently implemented ? 

[1] https://tools.ietf.org/html/rfc6749#section-6
[2] 
```
        OIDC_client = OIDC_CLIENTS[issuer]
        # assemble the request for the refresh token from the Identity Provider
        refresh_session_state = rndstr(50)
        OIDC_client.grant[refresh_session_state] = Grant()
        OIDC_client.grant[refresh_session_state].grant_expiration_time = time_util.utc_time_sans_frac() + 60
        OIDC_client.grant[refresh_session_state].code = "access_code"
        resp = AccessTokenResponse()
        resp["refresh_token"] = token_object.refresh_token
        OIDC_client.grant[refresh_session_state].tokens.append(Token(resp))
        oidc_tokens = OIDC_client.do_access_token_refresh(state=refresh_session_state)
```

**Comment by tpazderka** [comment]
No, this should be already working (unless I am missing something...).

In order to refresh a token, you need to have a previous token. That should also mean that the Grant should be still present.

**Comment by gumond** [comment]
It did not come to my mind to use the grant from the time the token was issued the first time ! Thank you, I will test it. As I am running this in a distributed environment, I have to save the session parameters (state,) in a DB and reinitialise the client with them, which I currently do using [1]. Is this the correct way to proceed ? 

[1] OIDC_client.authorization_request_info(request_args=auth_args)

**Comment by tpazderka** [comment]
If you use the `Consumer` class, there are methods `update`/`restore` which should do most of the work. The update/restore information about the client from the session database.

I guess that in your instance, you should be using `restore`.

**Comment by gumond** [comment]
If I am getting this right, the code around Consumer class makes assumptions on the DB table structure and hierarchy in use, right ? What if I need to specify the DB table and columns where the info should go ? 

In addition, does the token refresh mechanism really need Grant class initiated for the OIDC client ? Should not this be on the side of the Identity Provider to check if this refresh is allowed for that particular token and client ? It does not make sense to me why should I need a Grant when there are no state/nonce/code parameters exchanged in this particular case with the Identity Provider. 

What confirms my suspicion is that creating a mock _auth_query_string_  and mock _req_params_ dictionary (with mock state and nonce paremeters used further) in order to (re)initialise a client such as: 

```
        oidc_client.construct_AuthorizationRequest(request_args=req_params)
        # parsing the authorization query string by the Rucio OIDC Client (creates a Grant)
        oidc_client.parse_response(AuthorizationResponse,
                                   info=auth_query_string,
                                   sformat="urlencoded")
```

and then:

`oidc_client.do_access_token_refresh(state=state)`

works fine. I really think the re-init step above should not be necessary, but I will be glad to learn if you convince me otherwise ;)

**Comment by tpazderka** [comment]
> If I am getting this right, the code around Consumer class makes assumptions on the DB table structure and hierarchy in use, right ? What if I need to specify the DB table and columns where the info should go ?

Sort of. You can provide your own class that would hold such information as long as it has the same API.

> In addition, does the token refresh mechanism really need Grant class initiated for the OIDC client ? Should not this be on the side of the Identity Provider to check if this refresh is allowed for that particular token and client ? It does not make sense to me why should I need a Grant when there are no state/nonce/code parameters exchanged in this particular case with the Identity Provider.
> 
> What confirms my suspicion is that creating a mock _auth_query_string_ and mock _req_params_ dictionary (with mock state and nonce paremeters used further) in order to (re)initialise a client such as:
> 
> ```
>         oidc_client.construct_AuthorizationRequest(request_args=req_params)
>         # parsing the authorization query string by the Rucio OIDC Client (creates a Grant)
>         oidc_client.parse_response(AuthorizationResponse,
>                                    info=auth_query_string,
>                                    sformat="urlencoded")
> ```
> 
> and then:
> 
> `oidc_client.do_access_token_refresh(state=state)`
> 
> works fine. I really think the re-init step above should not be necessary, but I will be glad to learn if you convince me otherwise ;)

The check for refresh is definitely on the provider side.

The existing grant/token is used to pick up the correct refresh_token. Upon receive, they are stored in the database and then retrieved.
https://github.com/OpenIDC/pyoidc/blob/9309edf1caf18355434eeeb837817c82dad2d998/src/oic/oauth2/__init__.py#L451-L453
