### ISSUE TITLE
Failing integration tests on master

### ISSUE THREAD

**Issue by tpazderka** [OpenIDC/pyoidc#742]
Integration tests are failing on master due to nuked dependency from PyPi.

See https://github.com/openid-certification/oidctest/issues/217

**Comment by zandbelt** [comment]
things should be better now with https://github.com/openid-certification/oidctest/commit/10c6d9349a4fb60d9956650e457574533666c4af and the updates on otest master

**Comment by tpazderka** [comment]
Yes, the CI is passing now. Thanks for the fix!
