### ISSUE TITLE
After I make install, I have an error

### ISSUE THREAD

**Issue by ericliujian** [OpenIDC/pyoidc#750]
![20200624155711](https://user-images.githubusercontent.com/25019274/85621533-702ff580-b633-11ea-88a1-aed64662614b.png)

Please help.

**Comment by schlenk** [comment]
The pip error message tells the problem. Python 2.7 is no longer supported. You need at least Python 3.5.

**Comment by ericliujian** [comment]
I understand I need Python 3.5 at least, but I already install Python 3.8.2. I changed my default python to python3 not python2. Why it still give me the Python 2.7 error?
![20200626154122](https://user-images.githubusercontent.com/25019274/85894850-81a80780-b7c3-11ea-9729-f2c105751bdb.png)

**Comment by tpazderka** [comment]
The screenshot you have posted in your first comment is a result of running the code under 2.7. Are you sure, you are launching under the correct python version?
