### ISSUE TITLE
why user cannot change response_cls?

### ISSUE THREAD

**Issue by caffeinism** [OpenIDC/pyoidc#758]
now, do_*_request methods implemented like this.

https://github.com/OpenIDC/pyoidc/blob/53a246ae807046896ceae9a93add5fda520afe2b/src/oic/oauth2/__init__.py#L878

but some use case in oidc client, need to get raw id_token.

i hope to this method change like this

```
    response_cls = kwargs.get('response_cls', None) or self.message_factory.get_response_type("token_endpoint") 
```

isn't it clear?

**Comment by tpazderka** [comment]
You can provide your own `message_factory` that would return the appropriate `response_cls`. This should probably do what you aim for.
