### ISSUE TITLE
Deprecation warning for collections.abc

### ISSUE THREAD

**Issue by atremblay** [OpenIDC/pyoidc#773]
While the [master branch](https://github.com/OpenIDC/pyoidc/blob/62f8d753fa17c8b1f29f8be639cf0b33afb02498/src/oic/utils/sanitize.py#L2) (version 1.2.0) changed `from collections import Mapping` to `from collections.abc import Mapping`, the [latest release (1.2.1)](https://github.com/OpenIDC/pyoidc/blob/0bf07d010e224247b6dc7bceb3c04aa328ed263e/src/oic/utils/sanitize.py#L2) does not, it still has the old `from collections import Mapping`

It's as if [this commit](https://github.com/OpenIDC/pyoidc/commit/deabbebb56d23016ca1fc95a7f969c128b0a6c3e) didn't make it to the latest release.

**Comment by tpazderka** [comment]
The `1.2.1` was a bugfix release addressing a security vulnerability. For this reason, we intended for the smallest possible difference between the two versions.

**Comment by atremblay** [comment]
Just to be certain, while the master branch has version `1.2.0`, the corresponding release (tag `1.2.0`) doesn't have the correction either. It doesn't look like any available version has it.
I'm sorry if this is a dumb question, I am not sure how the branches and release are managed. That's probably totally normal, I'm just looking to have that warning out of my logs.

Thanks

**Comment by tpazderka** [comment]
The master still has the `1.2.0` version in the setup, but it wasn't released as a new version. So, no, the deprecation wasn't removed in any of the released version.
I still have a lot of work I would like to do before a new release but unfortunately very little time :(

**Comment by atremblay** [comment]
Cool, thanks for the response.
