### ISSUE TITLE
Interface or headless

### ISSUE THREAD

**Issue by datatalking** [OpenIDC/pyoidc#792]
So is this API setup a headless configuration or is there a gui we are supposed to use.

A screenshot of what it looks like would be massively helpful.

**Comment by schlenk** [comment]
What are you trying to do?

Setting up an OP? Setting up a RP? or using the client parts of the library?

There is no GUI for setting up things.

**Comment by datatalking** [comment]
I'm been working on five different builds right now and this (apparently) was one of several pieces that were referenced. I have no idea what it does. Was hoping for a picture or image of it being used, but it's just so nondescriptive that I've not got a clue as to its function. The project list ranges from multivariate regression, some Django website updates, pushing old code to the cloud, historical financial data analysis, social media analytics, financial modeling, and today building data pipelines.

I've re-read the description and the readme twice this morning and it's so nebulous (to me) that I can't even remember what this might have been connected to? My comments referenced an API setup but a setup for what? Auth verification for what?

**Comment by schlenk** [comment]
Maybe try some basic info about OpenID connect and OAuth2, there are a few around.

https://oauth.net/2/ has quite a few links to videos, the specifications and pictures how things work. 

pyoidc offers you a library to build most parts of that, like an Identity Provider (OP), a Relaying Party (RP, often some API you call authorized via OAuth2 Tokens) or to build a client for the OP/RP.

**Comment by datatalking** [comment]
@schlenk Thanks ! I'll add your comments to the list
