### ISSUE TITLE
How to decode and validate an id_token provided externally?

### ISSUE THREAD

**Issue by invokermain** [OpenIDC/pyoidc#795]
I've read through the source code and documentation but am struggling to implement my scenario.

In my scenario an `id_token` is passed to my client as a jwt (my client doesn't handle log in redirects etc). The client is already registered.

My client only needs to be able to validate this token against the oidc server (by decrypting the jwt?).

I can instantiate an `client = oic.Client(client_id=client_id, client_secret=client_secret)`, and pull the configuration from the server using `client.provider_config(issuer=issuer)`. But how do I take an `id_token = "wdJ2sdD...."` and validate it using my client?

Is this type of workflow supported?

**Comment by schlenk** [comment]
You should be able to use `client.verify_id_token()` for the final part of the validation. But that needs a decoded ID token. The basic decoding and validation is done in the `oic.oic.message.IDToken` class.

Untestet, but this should get you started:

```python
from oic.oic.message import IDToken
client.provider_config(issuer=issuer)
token = IDToken.from_jwt(data, keyjar=client.keyjar)

# Check the basics
token.verify(iss=issuer, client_id=client.client_id)

# Now check the extra stuff
authn_request = {
   "nonce": "your nonce",
   ...
}
client.verify_id_token(token, authn_request)
```

**Comment by invokermain** [comment]
This is really helpful thanks, the Keyjar component was the missing piece for me I think.
