### ISSUE TITLE
AttributeError: 'str' object has no attribute 'replaced' when doing access token refresh

### ISSUE THREAD

**Issue by infohash** [OpenIDC/pyoidc#804]
```python
from oic.oic import Client
from oic.utils.authn.client import CLIENT_AUTHN_METHOD

client = Client(client_authn_method=CLIENT_AUTHN_METHOD)

request_args = {
    'grant_type': 'refresh_token',
    'refresh_token': 'refresh_token123',
    'client_id': 'client_id123',
    'client_secret': 'client_secret123',
    'redirect_uri': self._redirect_uri
}

client.do_access_token_refresh(request_args=request_args,
    authn_method='client_secret_basic',
    token='refresh_token123',
    endpoint=self._client.token_endpoint
    )
```

Root Cause
------------

https://github.com/OpenIDC/pyoidc/blob/0d316fc0baca21b16164ef17fb275979d178f4b6/src/oic/oauth2/__init__.py#L930-L970

Up to here, I'm receiving new access token response. But the next line access `replaced` attribute of `token` which contains a string `refresh_token123` as passed above in `do_access_token_refresh`.

https://github.com/OpenIDC/pyoidc/blob/0d316fc0baca21b16164ef17fb275979d178f4b6/src/oic/oauth2/__init__.py#L971-L973

**Why this if statement exists here? Am I using `token` keyword argument incorrectly? When this if statement is commented out, it returns `response`.**

`token` is coming from here:

https://github.com/OpenIDC/pyoidc/blob/0d316fc0baca21b16164ef17fb275979d178f4b6/src/oic/oauth2/__init__.py#L945

https://github.com/OpenIDC/pyoidc/blob/0d316fc0baca21b16164ef17fb275979d178f4b6/src/oic/oauth2/__init__.py#L351-L353

This is why I've to pass `token` as an optional keyword argument of `**kwargs` in `do_access_token_refresh`. Otherwise this line of code handles `KeyError` exception and resorts to:

https://github.com/OpenIDC/pyoidc/blob/0d316fc0baca21b16164ef17fb275979d178f4b6/src/oic/oauth2/__init__.py#L351-L355

https://github.com/OpenIDC/pyoidc/blob/0d316fc0baca21b16164ef17fb275979d178f4b6/src/oic/oauth2/__init__.py#L345-L349

I don't have `state`, refreshing token doesn't require `state` either. So it raises `GrantError("No grant found for state:'%s'" % state)`.

**Comment by tpazderka** [comment]
The `token` kwarg is not a string but should be a [Token](https://github.com/OpenIDC/pyoidc/blob/0d316fc0baca21b16164ef17fb275979d178f4b6/src/oic/oauth2/grant.py#L12) instance.

**Comment by infohash** [comment]
Even if `Token` instance is provided, the if condition becomes `True` and this method is executed which raises `GrantError("No grant found for state:'%s'" % state)` as I've explained in my original post. I don't have `state` parameter at the time of making access token refresh.

https://github.com/OpenIDC/pyoidc/blob/0d316fc0baca21b16164ef17fb275979d178f4b6/src/oic/oauth2/__init__.py#L971-L973

https://github.com/OpenIDC/pyoidc/blob/0d316fc0baca21b16164ef17fb275979d178f4b6/src/oic/oauth2/__init__.py#L345-L349

Everything is fine before this if condition. I'm getting the new access token when I comment that out.

**Comment by infohash** [comment]
I have passed `Token` class instance as an argument and `replaced` attribute is by default `False` so that if condition never becomes `True`. Now it's working.

```python
from oic.oauth2.grant import Token

...

client.do_access_token_refresh(request_args=request_args,
    authn_method='client_secret_basic',
    token=Token(),
    endpoint=self._client.token_endpoint
 )
```

What's the appropriate usecase of passing `Token` instance like that?

**Comment by infohash** [comment]
I have passed `Token` class instance as an argument and `replaced` attribute is by default `False` so that if condition never becomes `True`. Now it's working.

```python
from oic.oauth2.grant import Token

...

client.do_access_token_refresh(request_args=request_args,
    authn_method='client_secret_basic',
    token=Token(),
    endpoint=self._client.token_endpoint
 )
```

What's the appropriate usecase of passing `Token` instance like that?

**Comment by tpazderka** [comment]
You need to add the refresh info to the instance:
```
token = Token(resp=AuthorizationResponse)
```
That should work...
