### ISSUE TITLE
NotAllowedValue: access_denied

### ISSUE THREAD

**Issue by mawe42** [OpenIDC/pyoidc#82]
I'm using the op1 and rp2 example servers to test out the pyoidc library. During setup, I forgot to properly configure the keys, so my OP failed when asked to issue an access token and responded with the error message '{"error_description": "Could not sign/encrypt id_token", "error": "access_denied"}'

However, on the RP side, the error I got was: NotAllowedValue: access_denied

It seems to be that the access token request code expects a TokenErrorResponse, but 'access_denied' is not a valid value for the error parameter of that response class. I'm not sure what the right approach is here. The RFC is a bit confusing for me... it mentions an error response for token requests in several places. At least one also includes "access_denied" as a valid error value, the other one doesn't.

So I'm not sure what to suggest. Maybe the c_allowed_values list of TokenErrorReponse should include 'access_denied' , or the endpoint code should raise an error with a valid "error" value.

**Comment by tpazderka** [comment]
As far as I can tell, this has been fixed in https://github.com/OpenIDC/pyoidc/commit/aedd78195f4d2d28a5f4a9007e996b091800ac78.
