### ISSUE TITLE
Wrong parameter used in the flow of end session request

### ISSUE THREAD

**Issue by infohash** [OpenIDC/pyoidc#826]
`oic.oic.Client.construct_EndSessionRequest` calls `_id_token_based` to add `raw_id_token`(JWT) into request args.

https://github.com/OpenIDC/pyoidc/blob/8bc957c814b97506d09fffd0881fe7d1e68f5095/src/oic/oic/__init__.py#L645-L647

The problem is here:

https://github.com/OpenIDC/pyoidc/blob/8bc957c814b97506d09fffd0881fe7d1e68f5095/src/oic/oic/__init__.py#L615-L629

You cannot send the keyword argument `prop` when calling `oic.oic.Client.do_end_session_request` so its value becomes `"id_token"`. But the key `id_token` will not be present in `request_args` because the end session request takes `id_token_hint` as the parameter name for the `raw_id_token`. So, the else condition becomes true and the request_args becomes:

```python
request_args["id_token"] = raw_id_token
```
IdP rejects this as a parameter for end session request.

# Expected Request Args Should Be

```python
request_args = {
    "id_token_hint": id_token_jwt,
    "post_logout_redirect_uri": "https://client.example.com/logout",
    "state": oic.rndstr()
}
```

Can you confirm if my findings are correct before I raise PR for this?

**Comment by infohash** [comment]
# Solution

The fix is simple. Just add the key `prop` to kwargs and its value will be `id_token_hint`. Here:

https://github.com/OpenIDC/pyoidc/blob/8bc957c814b97506d09fffd0881fe7d1e68f5095/src/oic/oic/__init__.py#L649-L659

```python
             if "id_token_hint" in request_args:
                 kwargs["prop"] = "id_token_hint"

             return self._id_token_based(request, request_args, extra_args, **kwargs)
```

I have also tested this. What do you think?

**Comment by tpazderka** [comment]
I suppose that you solution works as it would allow you to select the proper argument to pass.

But it might be better to make sure that the default is correct for each individual call. So my idea would rather be to set the default `prop` for the `construct_EndSessionRequest` to be `id_token_hint` and then allow to overwrite it from the higher level call.

**Comment by infohash** [comment]
@tpazderka In its test cases, you added `id_token` instead of `id_token_hint` and `redirect_url` instead of `post_logout_redirect_url`. Do you rememeber the reason behind that? I will overwrite but if that was intended, it could break things that I am not aware of.

https://github.com/OpenIDC/pyoidc/blob/8bc957c814b97506d09fffd0881fe7d1e68f5095/tests/test_oic.py#L407-L433

https://github.com/OpenIDC/pyoidc/blob/8bc957c814b97506d09fffd0881fe7d1e68f5095/tests/test_oic.py#L662-L686
