### ISSUE TITLE
type hints issue - python 3.11 compatibility

### ISSUE THREAD

**Issue by neoflex** [OpenIDC/pyoidc#827]
While trying to use the library with python 3.11 we identified at least one issue caused by type hints checks performed in the `__setattr__` method of `utils/settings.py`. 

We get the following error when client_cert is None (default value). 

> oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).

Not tested but setting the type hints as Optional might fix it.

**Comment by tpazderka** [comment]
Isn't that rather caused by recent changes in mypy and not allowing implicit `Optional` in function definitions?

I do agree that we should type it properly but it might not be related to python 3.11.

**Comment by neoflex** [comment]
see this changelog in Python 3.11 release:

> [typing.get_type_hints()](https://docs.python.org/3.11/library/typing.html#typing.get_type_hints) no longer adds [Optional](https://docs.python.org/3.11/library/typing.html#typing.Optional) to parameters with None as a default.

https://github.com/python/cpython/issues/90353

**Comment by tpazderka** [comment]
Added an official support for python 3.11.

**Comment by gaardiolor** [comment]
When will there be a new pip package ? (Latest version is > 6 months old) 

thanks!

**Comment by pkking** [comment]
Meet same issue, my workaroud is `pip install https://github.com/OpenIDC/pyoidc/archive/master.zip`
