### ISSUE TITLE
birthdate miss lead a exception

### ISSUE THREAD

**Issue by pkking** [OpenIDC/pyoidc#830]
Hi, im using pyoidc with [authing](https://www.authing.cn/)，if the app request scope included birthdate, and the provider do not reply a birthdate, it will go a exception as the `verify` do not check if it's a NoneType
```
  def verify(self, **kwargs):
        super().verify(**kwargs)

        if "birthdate" in self:
            # Either YYYY-MM-DD or just YYYY or 0000-MM-DD
            try:
                time.strptime(self["birthdate"], "%Y-%m-%d")
            except ValueError:
                try:
                    time.strptime(self["birthdate"], "%Y")
                except ValueError:
                    try:
                        time.strptime(self["birthdate"], "0000-%m-%d")
                    except ValueError:
                        raise VerificationError("Birthdate format error", self)
```

the userinfo returned by provider is something like this
```
'userinfo': {'name': None, 'nickname': None, 'birthdate': None ...}
```
actually i do not care for the `birthdate`, is there any work-around ?

**Comment by schlenk** [comment]
A ``None`` type is not really encouraged by the specification, but not forbidden either, so the overly strict verification is a bug.

https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse states:
> If a Claim is not returned, that Claim Name SHOULD be omitted from the JSON object representing the Claims; it SHOULD NOT be present with a null or empty string value. 

it is SHOULD NOT, not MUST NOT, so the OP is okay. But you could open an Issue there too, to omit empty claims.

Depending on how you use the client to fetch the userinfo, you may subclass `oic.oic.message.OpenIDSchema` to change the verification logic and use that subclass as `user_info_schema` kwarg for the `do_userinfo_request()` call of the client.

**Comment by pkking** [comment]
okay, maybe i can submit a PR on this :)
