### ISSUE TITLE
Create python 3.11 compatible release for pypi

### ISSUE THREAD

**Issue by schlenk** [OpenIDC/pyoidc#839]
The issue fixed with https://github.com/OpenIDC/pyoidc/issues/827 does not only affect type checking with mypy.

It actually prevents users to run the Client code, due to the typing usage in the settings setattr method.

```
site-packages\oic\oic\__init__.py", line 354, in __init__
    self.settings = settings or OicClientSettings()
site-packages\oic\utils\settings.py", line 96, in __init__
     super().__init__(
site-packages\oic\utils\settings.py", line 51, in __init__
     self.client_cert = client_cert
site-packages\oic\utils\settings.py", line 73, in __setattr__
     raise SettingsException(

oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).
```

So publishing a fixed version to pypi would be quite useful.

I could try to prepare things, but at least for the actual upload to pypi i think either @tpazderka or @rohe need to do the push.

See also: https://github.com/OpenIDC/pyoidc/issues/838

**Comment by tpazderka** [comment]
I will do it later today.

**Comment by tpazderka** [comment]
Uploaded.
